// Code generated by protoc-gen-go.
// source: configuration/appconfig.proto
// DO NOT EDIT!

/*
Package configuration is a generated protocol buffer package.

It is generated from these files:
	configuration/appconfig.proto
	configuration/contractflow.proto
	configuration/globalconfig.proto
	configuration/modelconfig.proto

It has these top-level messages:
	NodeConfig
	NodeConfigs
	APPConfig
	ContractStep
	ContractFlow
	APPConfigBrief
	CommercialOrg
	FinancingRelation
	Banks
	BankLoanRelation
*/
package configuration

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import protos "github.com/xncc/protos/common"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// ======================================================私有配置信息=======================================
// 节点信息
type NodeConfig struct {
	// 一般 情况，有多少个 peer就会有多少个 sdk， 每个 sdk 带有一个 user
	Pem         string `protobuf:"bytes,1,opt,name=pem" json:"pem,omitempty"`
	SdkCert     string `protobuf:"bytes,2,opt,name=sdkCert" json:"sdkCert,omitempty"`
	SdkUserName string `protobuf:"bytes,3,opt,name=sdkUserName" json:"sdkUserName,omitempty"`
	SdkUserPWD  string `protobuf:"bytes,4,opt,name=sdkUserPWD" json:"sdkUserPWD,omitempty"`
}

func (m *NodeConfig) Reset()                    { *m = NodeConfig{} }
func (m *NodeConfig) String() string            { return proto.CompactTextString(m) }
func (*NodeConfig) ProtoMessage()               {}
func (*NodeConfig) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *NodeConfig) GetPem() string {
	if m != nil {
		return m.Pem
	}
	return ""
}

func (m *NodeConfig) GetSdkCert() string {
	if m != nil {
		return m.SdkCert
	}
	return ""
}

func (m *NodeConfig) GetSdkUserName() string {
	if m != nil {
		return m.SdkUserName
	}
	return ""
}

func (m *NodeConfig) GetSdkUserPWD() string {
	if m != nil {
		return m.SdkUserPWD
	}
	return ""
}

type NodeConfigs struct {
	NodeConfigs []*NodeConfig `protobuf:"bytes,1,rep,name=nodeConfigs" json:"nodeConfigs,omitempty"`
}

func (m *NodeConfigs) Reset()                    { *m = NodeConfigs{} }
func (m *NodeConfigs) String() string            { return proto.CompactTextString(m) }
func (*NodeConfigs) ProtoMessage()               {}
func (*NodeConfigs) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *NodeConfigs) GetNodeConfigs() []*NodeConfig {
	if m != nil {
		return m.NodeConfigs
	}
	return nil
}

// APPConfig 是不公开的
type APPConfig struct {
	AppId            string              `protobuf:"bytes,1,opt,name=appId" json:"appId,omitempty"`
	AppKey           string              `protobuf:"bytes,2,opt,name=appKey" json:"appKey,omitempty"`
	AppName          string              `protobuf:"bytes,3,opt,name=appName" json:"appName,omitempty"`
	AppType          string              `protobuf:"bytes,4,opt,name=appType" json:"appType,omitempty"`
	AppCallbackUrl   string              `protobuf:"bytes,5,opt,name=appCallbackUrl" json:"appCallbackUrl,omitempty"`
	SecureIp         string              `protobuf:"bytes,6,opt,name=secureIp" json:"secureIp,omitempty"`
	OrgName          string              `protobuf:"bytes,7,opt,name=orgName" json:"orgName,omitempty"`
	OrgAddress       string              `protobuf:"bytes,8,opt,name=orgAddress" json:"orgAddress,omitempty"`
	BizContactName   string              `protobuf:"bytes,9,opt,name=bizContactName" json:"bizContactName,omitempty"`
	BizContactTel    string              `protobuf:"bytes,10,opt,name=bizContactTel" json:"bizContactTel,omitempty"`
	BizContaceEmail  string              `protobuf:"bytes,11,opt,name=bizContaceEmail" json:"bizContaceEmail,omitempty"`
	TechContactName  string              `protobuf:"bytes,12,opt,name=techContactName" json:"techContactName,omitempty"`
	TechContactTel   string              `protobuf:"bytes,13,opt,name=techContactTel" json:"techContactTel,omitempty"`
	TechContactEmail string              `protobuf:"bytes,14,opt,name=techContactEmail" json:"techContactEmail,omitempty"`
	OpInfo           *protos.OperateInfo `protobuf:"bytes,15,opt,name=opInfo" json:"opInfo,omitempty"`
}

func (m *APPConfig) Reset()                    { *m = APPConfig{} }
func (m *APPConfig) String() string            { return proto.CompactTextString(m) }
func (*APPConfig) ProtoMessage()               {}
func (*APPConfig) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *APPConfig) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *APPConfig) GetAppKey() string {
	if m != nil {
		return m.AppKey
	}
	return ""
}

func (m *APPConfig) GetAppName() string {
	if m != nil {
		return m.AppName
	}
	return ""
}

func (m *APPConfig) GetAppType() string {
	if m != nil {
		return m.AppType
	}
	return ""
}

func (m *APPConfig) GetAppCallbackUrl() string {
	if m != nil {
		return m.AppCallbackUrl
	}
	return ""
}

func (m *APPConfig) GetSecureIp() string {
	if m != nil {
		return m.SecureIp
	}
	return ""
}

func (m *APPConfig) GetOrgName() string {
	if m != nil {
		return m.OrgName
	}
	return ""
}

func (m *APPConfig) GetOrgAddress() string {
	if m != nil {
		return m.OrgAddress
	}
	return ""
}

func (m *APPConfig) GetBizContactName() string {
	if m != nil {
		return m.BizContactName
	}
	return ""
}

func (m *APPConfig) GetBizContactTel() string {
	if m != nil {
		return m.BizContactTel
	}
	return ""
}

func (m *APPConfig) GetBizContaceEmail() string {
	if m != nil {
		return m.BizContaceEmail
	}
	return ""
}

func (m *APPConfig) GetTechContactName() string {
	if m != nil {
		return m.TechContactName
	}
	return ""
}

func (m *APPConfig) GetTechContactTel() string {
	if m != nil {
		return m.TechContactTel
	}
	return ""
}

func (m *APPConfig) GetTechContactEmail() string {
	if m != nil {
		return m.TechContactEmail
	}
	return ""
}

func (m *APPConfig) GetOpInfo() *protos.OperateInfo {
	if m != nil {
		return m.OpInfo
	}
	return nil
}

func init() {
	proto.RegisterType((*NodeConfig)(nil), "protos.NodeConfig")
	proto.RegisterType((*NodeConfigs)(nil), "protos.NodeConfigs")
	proto.RegisterType((*APPConfig)(nil), "protos.APPConfig")
}

func init() { proto.RegisterFile("configuration/appconfig.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 439 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x64, 0x93, 0x6d, 0x6b, 0xdb, 0x30,
	0x10, 0xc7, 0xc9, 0xd2, 0xa6, 0xcd, 0x79, 0x7d, 0x40, 0x1d, 0x43, 0x14, 0x36, 0x42, 0x08, 0x23,
	0x6c, 0x60, 0x43, 0xb7, 0x2f, 0xd0, 0x79, 0x7b, 0x11, 0x36, 0xba, 0x10, 0x5a, 0x06, 0x7b, 0xa7,
	0xc8, 0xaa, 0x6b, 0x62, 0x4b, 0x87, 0xe4, 0x90, 0xb6, 0x1f, 0x62, 0x9f, 0x79, 0xe8, 0xc1, 0xb5,
	0x9d, 0xbd, 0x72, 0xfe, 0xbf, 0xfb, 0x45, 0x77, 0x67, 0x2c, 0x78, 0xc7, 0x95, 0xbc, 0x2f, 0xf2,
	0xad, 0x66, 0x75, 0xa1, 0x64, 0xc2, 0x10, 0x3d, 0x88, 0x51, 0xab, 0x5a, 0x91, 0x91, 0x7b, 0x98,
	0xcb, 0x0b, 0xae, 0xaa, 0x4a, 0xc9, 0xc4, 0x3f, 0x7c, 0x71, 0xfa, 0x0c, 0x70, 0xa3, 0x32, 0x91,
	0xba, 0x3f, 0x90, 0x73, 0x18, 0xa2, 0xa8, 0xe8, 0x60, 0x32, 0x98, 0x8f, 0x57, 0xf6, 0x27, 0xa1,
	0x70, 0x64, 0xb2, 0x4d, 0x2a, 0x74, 0x4d, 0x5f, 0x39, 0xda, 0x44, 0x32, 0x81, 0xc8, 0x64, 0x9b,
	0x3b, 0x23, 0xf4, 0x0d, 0xab, 0x04, 0x1d, 0xba, 0x6a, 0x17, 0x91, 0xf7, 0x00, 0x21, 0x2e, 0x7f,
	0x7f, 0xa3, 0x07, 0x4e, 0xe8, 0x90, 0x69, 0x0a, 0x51, 0xdb, 0xdb, 0x90, 0x2f, 0x10, 0xc9, 0x36,
	0xd2, 0xc1, 0x64, 0x38, 0x8f, 0xae, 0x88, 0x9f, 0xd3, 0xc4, 0xad, 0xb9, 0xea, 0x6a, 0xd3, 0xbf,
	0x07, 0x30, 0xbe, 0x5e, 0x2e, 0xc3, 0x02, 0x6f, 0xe0, 0x90, 0x21, 0x2e, 0xb2, 0xb0, 0x82, 0x0f,
	0xe4, 0x2d, 0x8c, 0x18, 0xe2, 0x0f, 0xf1, 0x14, 0x76, 0x08, 0xc9, 0x2e, 0xc7, 0x10, 0x3b, 0xe3,
	0x37, 0x31, 0x54, 0x6e, 0x9f, 0x50, 0x84, 0xb9, 0x9b, 0x48, 0x3e, 0xc0, 0x29, 0x43, 0x4c, 0x59,
	0x59, 0xae, 0x19, 0xdf, 0xdc, 0xe9, 0x92, 0x1e, 0x3a, 0x61, 0x8f, 0x92, 0x4b, 0x38, 0x36, 0x82,
	0x6f, 0xb5, 0x58, 0x20, 0x1d, 0x39, 0xe3, 0x25, 0xdb, 0xd3, 0x95, 0xce, 0x5d, 0xdf, 0x23, 0x7f,
	0x7a, 0x88, 0xf6, 0x95, 0x29, 0x9d, 0x5f, 0x67, 0x99, 0x16, 0xc6, 0xd0, 0x63, 0xff, 0xca, 0x5a,
	0x62, 0xbb, 0xaf, 0x8b, 0xe7, 0x54, 0xc9, 0x9a, 0xf1, 0xda, 0x1d, 0x30, 0xf6, 0xdd, 0xfb, 0x94,
	0xcc, 0xe0, 0xa4, 0x25, 0xb7, 0xa2, 0xa4, 0xe0, 0xb4, 0x3e, 0x24, 0x73, 0x38, 0x7b, 0x01, 0xe2,
	0x7b, 0xc5, 0x8a, 0x92, 0x46, 0xce, 0xdb, 0xc7, 0xd6, 0xac, 0x05, 0x7f, 0xe8, 0x36, 0x7e, 0xed,
	0xcd, 0x3d, 0x6c, 0x27, 0xec, 0x20, 0xdb, 0xfa, 0xc4, 0x4f, 0xd8, 0xa7, 0xe4, 0x23, 0x9c, 0x77,
	0x88, 0x6f, 0x7e, 0xea, 0xcc, 0xff, 0x38, 0xf9, 0x04, 0x23, 0x85, 0x0b, 0x79, 0xaf, 0xe8, 0xd9,
	0x64, 0x30, 0x8f, 0xae, 0x2e, 0x9a, 0x8f, 0xe2, 0x17, 0x0a, 0xcd, 0x6a, 0x61, 0x4b, 0xab, 0xa0,
	0x7c, 0xfd, 0x09, 0x33, 0xae, 0xaa, 0xf8, 0xb1, 0x60, 0x32, 0x97, 0x2c, 0xde, 0xed, 0x76, 0x8d,
	0xdd, 0xbb, 0x26, 0x7f, 0x66, 0x79, 0x51, 0x3f, 0x6c, 0xd7, 0x31, 0x57, 0x55, 0xf2, 0x28, 0x39,
	0x4f, 0xbc, 0x95, 0xf4, 0xac, 0xb5, 0xbf, 0x3c, 0x9f, 0xff, 0x05, 0x00, 0x00, 0xff, 0xff, 0xbe,
	0x93, 0x30, 0xb0, 0x64, 0x03, 0x00, 0x00,
}
