// Code generated by protoc-gen-go.
// source: configuration/modelconfig.proto
// DO NOT EDIT!

package configuration

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import protos "github.com/xncc/protos/common"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// ======================================================三方关系配置信息=======================================
// 机构信息，在入三方账本时放到账本中公开
type CommercialOrg struct {
	AppId   string `protobuf:"bytes,1,opt,name=appId" json:"appId,omitempty"`
	AppName string `protobuf:"bytes,2,opt,name=appName" json:"appName,omitempty"`
	AppType string `protobuf:"bytes,3,opt,name=appType" json:"appType,omitempty"`
	// 如果三证合一只需要填写统一社会信用代码
	OrgCode                      string `protobuf:"bytes,4,opt,name=org_code,json=orgCode" json:"org_code,omitempty"`
	RegistedNo                   string `protobuf:"bytes,5,opt,name=registed_no,json=registedNo" json:"registed_no,omitempty"`
	TaxRegistrationCertificateNo string `protobuf:"bytes,6,opt,name=tax_registration_certificate_no,json=taxRegistrationCertificateNo" json:"tax_registration_certificate_no,omitempty"`
	// 机构基本信息
	OrgCorporate    string                            `protobuf:"bytes,7,opt,name=org_corporate,json=orgCorporate" json:"org_corporate,omitempty"`
	ContactPerson   []*CommercialOrg_OrgContactPerson `protobuf:"bytes,8,rep,name=contact_person,json=contactPerson" json:"contact_person,omitempty"`
	Introduction    string                            `protobuf:"bytes,9,opt,name=introduction" json:"introduction,omitempty"`
	RegisterAddress string                            `protobuf:"bytes,10,opt,name=register_address,json=registerAddress" json:"register_address,omitempty"`
	CurrentAddress  string                            `protobuf:"bytes,11,opt,name=current_address,json=currentAddress" json:"current_address,omitempty"`
	Telephone       string                            `protobuf:"bytes,12,opt,name=telephone" json:"telephone,omitempty"`
	Email           string                            `protobuf:"bytes,13,opt,name=email" json:"email,omitempty"`
	OrgCategory     string                            `protobuf:"bytes,14,opt,name=org_category,json=orgCategory" json:"org_category,omitempty"`
	// 三方账本时:
	//           供应商维护两个账户
	//           核心企业维护一个还款账户到结算账户
	//           保理公司维护两个账户:一个放款账户到结算账户,一个收还款账户
	// 双方账本时：
	//           保理公司维护两个账户
	//           保理公司维护两个账户:一个放款账户到结算账户,一个收还款账户
	SettlementAccount *protos.OrgBankAccount `protobuf:"bytes,15,opt,name=settlement_account,json=settlementAccount" json:"settlement_account,omitempty"`
	PolicyAccount     *protos.OrgBankAccount `protobuf:"bytes,16,opt,name=policy_account,json=policyAccount" json:"policy_account,omitempty"`
	OrgFiles          *protos.LedgerFileMap  `protobuf:"bytes,17,opt,name=org_files,json=orgFiles" json:"org_files,omitempty"`
	OperateInfo       *protos.OperateInfo    `protobuf:"bytes,18,opt,name=operate_info,json=operateInfo" json:"operate_info,omitempty"`
}

func (m *CommercialOrg) Reset()                    { *m = CommercialOrg{} }
func (m *CommercialOrg) String() string            { return proto.CompactTextString(m) }
func (*CommercialOrg) ProtoMessage()               {}
func (*CommercialOrg) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{0} }

func (m *CommercialOrg) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *CommercialOrg) GetAppName() string {
	if m != nil {
		return m.AppName
	}
	return ""
}

func (m *CommercialOrg) GetAppType() string {
	if m != nil {
		return m.AppType
	}
	return ""
}

func (m *CommercialOrg) GetOrgCode() string {
	if m != nil {
		return m.OrgCode
	}
	return ""
}

func (m *CommercialOrg) GetRegistedNo() string {
	if m != nil {
		return m.RegistedNo
	}
	return ""
}

func (m *CommercialOrg) GetTaxRegistrationCertificateNo() string {
	if m != nil {
		return m.TaxRegistrationCertificateNo
	}
	return ""
}

func (m *CommercialOrg) GetOrgCorporate() string {
	if m != nil {
		return m.OrgCorporate
	}
	return ""
}

func (m *CommercialOrg) GetContactPerson() []*CommercialOrg_OrgContactPerson {
	if m != nil {
		return m.ContactPerson
	}
	return nil
}

func (m *CommercialOrg) GetIntroduction() string {
	if m != nil {
		return m.Introduction
	}
	return ""
}

func (m *CommercialOrg) GetRegisterAddress() string {
	if m != nil {
		return m.RegisterAddress
	}
	return ""
}

func (m *CommercialOrg) GetCurrentAddress() string {
	if m != nil {
		return m.CurrentAddress
	}
	return ""
}

func (m *CommercialOrg) GetTelephone() string {
	if m != nil {
		return m.Telephone
	}
	return ""
}

func (m *CommercialOrg) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *CommercialOrg) GetOrgCategory() string {
	if m != nil {
		return m.OrgCategory
	}
	return ""
}

func (m *CommercialOrg) GetSettlementAccount() *protos.OrgBankAccount {
	if m != nil {
		return m.SettlementAccount
	}
	return nil
}

func (m *CommercialOrg) GetPolicyAccount() *protos.OrgBankAccount {
	if m != nil {
		return m.PolicyAccount
	}
	return nil
}

func (m *CommercialOrg) GetOrgFiles() *protos.LedgerFileMap {
	if m != nil {
		return m.OrgFiles
	}
	return nil
}

func (m *CommercialOrg) GetOperateInfo() *protos.OperateInfo {
	if m != nil {
		return m.OperateInfo
	}
	return nil
}

// 机构联系人
type CommercialOrg_OrgContactPerson struct {
	Name      string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Telephone string `protobuf:"bytes,2,opt,name=telephone" json:"telephone,omitempty"`
	Email     string `protobuf:"bytes,3,opt,name=email" json:"email,omitempty"`
}

func (m *CommercialOrg_OrgContactPerson) Reset()         { *m = CommercialOrg_OrgContactPerson{} }
func (m *CommercialOrg_OrgContactPerson) String() string { return proto.CompactTextString(m) }
func (*CommercialOrg_OrgContactPerson) ProtoMessage()    {}
func (*CommercialOrg_OrgContactPerson) Descriptor() ([]byte, []int) {
	return fileDescriptor3, []int{0, 0}
}

func (m *CommercialOrg_OrgContactPerson) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CommercialOrg_OrgContactPerson) GetTelephone() string {
	if m != nil {
		return m.Telephone
	}
	return ""
}

func (m *CommercialOrg_OrgContactPerson) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

// 三方机构关系上链数据定义
type FinancingRelation struct {
	LedgerId string `protobuf:"bytes,1,opt,name=ledger_id,json=ledgerId" json:"ledger_id,omitempty"`
	// 三方机构的信息
	// 供应商需要在扩展字段中保留供应商扩展信息
	Supplier   *CommercialOrg `protobuf:"bytes,2,opt,name=supplier" json:"supplier,omitempty"`
	Enterprise *CommercialOrg `protobuf:"bytes,3,opt,name=enterprise" json:"enterprise,omitempty"`
	Factoring  *CommercialOrg `protobuf:"bytes,4,opt,name=factoring" json:"factoring,omitempty"`
	// 三方机构关系确立时可以设定默认的融资利率
	Rate              int64                `protobuf:"varint,5,opt,name=rate" json:"rate,omitempty"`
	OrderFilesEncrypt []*protos.LedgerFile `protobuf:"bytes,6,rep,name=order_files_encrypt,json=orderFilesEncrypt" json:"order_files_encrypt,omitempty"`
	// 三方机构关系确立的相关合同文件
	OrderFiles *protos.LedgerFileMap `protobuf:"bytes,7,opt,name=order_files,json=orderFiles" json:"order_files,omitempty"`
	// 保理向银行融资贷款时,勾选此三方的融资订单为质押
	// 银行需要拥有此三方账本,此字段只是备注记录,不做他用
	Banks *Banks `protobuf:"bytes,8,opt,name=banks" json:"banks,omitempty"`
}

func (m *FinancingRelation) Reset()                    { *m = FinancingRelation{} }
func (m *FinancingRelation) String() string            { return proto.CompactTextString(m) }
func (*FinancingRelation) ProtoMessage()               {}
func (*FinancingRelation) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{1} }

func (m *FinancingRelation) GetLedgerId() string {
	if m != nil {
		return m.LedgerId
	}
	return ""
}

func (m *FinancingRelation) GetSupplier() *CommercialOrg {
	if m != nil {
		return m.Supplier
	}
	return nil
}

func (m *FinancingRelation) GetEnterprise() *CommercialOrg {
	if m != nil {
		return m.Enterprise
	}
	return nil
}

func (m *FinancingRelation) GetFactoring() *CommercialOrg {
	if m != nil {
		return m.Factoring
	}
	return nil
}

func (m *FinancingRelation) GetRate() int64 {
	if m != nil {
		return m.Rate
	}
	return 0
}

func (m *FinancingRelation) GetOrderFilesEncrypt() []*protos.LedgerFile {
	if m != nil {
		return m.OrderFilesEncrypt
	}
	return nil
}

func (m *FinancingRelation) GetOrderFiles() *protos.LedgerFileMap {
	if m != nil {
		return m.OrderFiles
	}
	return nil
}

func (m *FinancingRelation) GetBanks() *Banks {
	if m != nil {
		return m.Banks
	}
	return nil
}

// 银行列表
type Banks struct {
	Banks []*protos.AppVo `protobuf:"bytes,1,rep,name=banks" json:"banks,omitempty"`
}

func (m *Banks) Reset()                    { *m = Banks{} }
func (m *Banks) String() string            { return proto.CompactTextString(m) }
func (*Banks) ProtoMessage()               {}
func (*Banks) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{2} }

func (m *Banks) GetBanks() []*protos.AppVo {
	if m != nil {
		return m.Banks
	}
	return nil
}

// 银行保理双方关系上链数据定义
type BankLoanRelation struct {
	LedgerId string `protobuf:"bytes,1,opt,name=ledger_id,json=ledgerId" json:"ledger_id,omitempty"`
	// 银行和保理双方机构的信息
	Factoring *CommercialOrg `protobuf:"bytes,2,opt,name=factoring" json:"factoring,omitempty"`
	BankInfo  *CommercialOrg `protobuf:"bytes,3,opt,name=bank_info,json=bankInfo" json:"bank_info,omitempty"`
	// 双方机构关系确立时可以设定默认的融资利率
	Rate int64 `protobuf:"varint,4,opt,name=rate" json:"rate,omitempty"`
	// 双方机构关系确立的相关合同文件
	OrderFiles *protos.LedgerFileMap `protobuf:"bytes,5,opt,name=order_files,json=orderFiles" json:"order_files,omitempty"`
}

func (m *BankLoanRelation) Reset()                    { *m = BankLoanRelation{} }
func (m *BankLoanRelation) String() string            { return proto.CompactTextString(m) }
func (*BankLoanRelation) ProtoMessage()               {}
func (*BankLoanRelation) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{3} }

func (m *BankLoanRelation) GetLedgerId() string {
	if m != nil {
		return m.LedgerId
	}
	return ""
}

func (m *BankLoanRelation) GetFactoring() *CommercialOrg {
	if m != nil {
		return m.Factoring
	}
	return nil
}

func (m *BankLoanRelation) GetBankInfo() *CommercialOrg {
	if m != nil {
		return m.BankInfo
	}
	return nil
}

func (m *BankLoanRelation) GetRate() int64 {
	if m != nil {
		return m.Rate
	}
	return 0
}

func (m *BankLoanRelation) GetOrderFiles() *protos.LedgerFileMap {
	if m != nil {
		return m.OrderFiles
	}
	return nil
}

func init() {
	proto.RegisterType((*CommercialOrg)(nil), "protos.CommercialOrg")
	proto.RegisterType((*CommercialOrg_OrgContactPerson)(nil), "protos.CommercialOrg.OrgContactPerson")
	proto.RegisterType((*FinancingRelation)(nil), "protos.FinancingRelation")
	proto.RegisterType((*Banks)(nil), "protos.Banks")
	proto.RegisterType((*BankLoanRelation)(nil), "protos.BankLoanRelation")
}

func init() { proto.RegisterFile("configuration/modelconfig.proto", fileDescriptor3) }

var fileDescriptor3 = []byte{
	// 763 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x8c, 0x55, 0x4d, 0x6f, 0x1b, 0x37,
	0x10, 0x85, 0x2c, 0xcb, 0x91, 0x46, 0x92, 0x3f, 0xe8, 0xb6, 0x60, 0xd3, 0x00, 0x76, 0x9d, 0xa0,
	0x75, 0x81, 0x42, 0x42, 0x15, 0x34, 0xb7, 0x1e, 0x6c, 0xc3, 0x01, 0x0c, 0x38, 0x76, 0xb1, 0x28,
	0x7a, 0xc8, 0x65, 0x41, 0x73, 0x47, 0x1b, 0x22, 0xbb, 0x1c, 0x82, 0x4b, 0xc1, 0xd2, 0xbd, 0x3f,
	0xb5, 0xd7, 0xfe, 0x87, 0x82, 0xa4, 0x56, 0x5a, 0x25, 0x90, 0xe1, 0xd3, 0xee, 0xbc, 0x79, 0x6f,
	0x39, 0x7c, 0x33, 0x83, 0x85, 0x13, 0x49, 0x7a, 0xaa, 0xf2, 0x99, 0x15, 0x4e, 0x91, 0x1e, 0x97,
	0x94, 0x61, 0x11, 0xa1, 0x91, 0xb1, 0xe4, 0x88, 0xed, 0x85, 0x47, 0xf5, 0xf2, 0x58, 0x52, 0x59,
	0x92, 0x1e, 0xc7, 0x47, 0x4c, 0x9e, 0xfd, 0xb7, 0x07, 0xc3, 0x2b, 0x2a, 0x4b, 0xb4, 0x52, 0x89,
	0xe2, 0xde, 0xe6, 0xec, 0x1b, 0xe8, 0x08, 0x63, 0x6e, 0x32, 0xde, 0x3a, 0x6d, 0x9d, 0xf7, 0x92,
	0x18, 0x30, 0x0e, 0x2f, 0x84, 0x31, 0x77, 0xa2, 0x44, 0xbe, 0x13, 0xf0, 0x3a, 0x5c, 0x66, 0xfe,
	0x5a, 0x18, 0xe4, 0xed, 0x55, 0xc6, 0x87, 0xec, 0x7b, 0xe8, 0x92, 0xcd, 0x53, 0x49, 0x19, 0xf2,
	0xdd, 0x98, 0x22, 0x9b, 0x5f, 0x51, 0x86, 0xec, 0x04, 0xfa, 0x16, 0x73, 0x55, 0x39, 0xcc, 0x52,
	0x4d, 0xbc, 0x13, 0xb2, 0x50, 0x43, 0x77, 0xc4, 0xae, 0xe1, 0xc4, 0x89, 0x79, 0x1a, 0x91, 0x78,
	0xb5, 0x54, 0xa2, 0x75, 0x6a, 0xaa, 0xa4, 0x70, 0xe8, 0x45, 0x7b, 0x41, 0xf4, 0xca, 0x89, 0x79,
	0xd2, 0x60, 0x5d, 0xad, 0x49, 0x77, 0xc4, 0x5e, 0xc3, 0x30, 0x96, 0x60, 0x0d, 0x59, 0xe1, 0x90,
	0xbf, 0x08, 0xa2, 0x41, 0xa8, 0x63, 0x89, 0xb1, 0x0f, 0xb0, 0x2f, 0x49, 0x3b, 0x21, 0x5d, 0x6a,
	0xd0, 0x56, 0xa4, 0x79, 0xf7, 0xb4, 0x7d, 0xde, 0x9f, 0xfc, 0x14, 0x3d, 0xaa, 0x46, 0x1b, 0x06,
	0x8d, 0xee, 0xbd, 0x36, 0xd0, 0xff, 0x0c, 0xec, 0x64, 0x28, 0x9b, 0x21, 0x3b, 0x83, 0x81, 0xd2,
	0xce, 0x52, 0x36, 0x93, 0xbe, 0x20, 0xde, 0x8b, 0x47, 0x36, 0x31, 0xf6, 0x0b, 0x1c, 0x2e, 0x2f,
	0x6b, 0x53, 0x91, 0x65, 0x16, 0xab, 0x8a, 0x43, 0xe0, 0x1d, 0xd4, 0xf8, 0x45, 0x84, 0xd9, 0xcf,
	0x70, 0x20, 0x67, 0xd6, 0xa2, 0x76, 0x2b, 0x66, 0x3f, 0x30, 0xf7, 0x97, 0x70, 0x4d, 0x7c, 0x05,
	0x3d, 0x87, 0x05, 0x9a, 0x4f, 0xa4, 0x91, 0x0f, 0x02, 0x65, 0x0d, 0xf8, 0xb6, 0x62, 0x29, 0x54,
	0xc1, 0x87, 0xb1, 0xad, 0x21, 0x60, 0x3f, 0xc2, 0x20, 0xf8, 0x23, 0x1c, 0xe6, 0x64, 0x17, 0x7c,
	0x3f, 0x24, 0xfb, 0xde, 0x9e, 0x25, 0xc4, 0xae, 0x81, 0x55, 0xe8, 0x5c, 0x81, 0x65, 0x28, 0x41,
	0x4a, 0x9a, 0x69, 0xc7, 0x0f, 0x4e, 0x5b, 0xe7, 0xfd, 0xc9, 0x77, 0xb5, 0x43, 0xf7, 0x36, 0xbf,
	0x14, 0xfa, 0xf3, 0x45, 0xcc, 0x26, 0x47, 0x6b, 0xc5, 0x12, 0x62, 0x7f, 0xc0, 0xbe, 0xa1, 0x42,
	0xc9, 0xc5, 0xea, 0x13, 0x87, 0x4f, 0x7e, 0x62, 0x18, 0xd9, 0xb5, 0x7c, 0x02, 0x3d, 0x5f, 0xe8,
	0x54, 0x15, 0x58, 0xf1, 0xa3, 0xa0, 0xfc, 0xb6, 0x56, 0xde, 0x62, 0x96, 0xa3, 0x7d, 0xaf, 0x0a,
	0xfc, 0x20, 0x4c, 0xe2, 0x67, 0xce, 0xbf, 0x57, 0xec, 0x1d, 0x0c, 0xc8, 0xa0, 0x6f, 0x71, 0xaa,
	0xf4, 0x94, 0x38, 0x0b, 0xb2, 0xe3, 0xd5, 0x81, 0x31, 0x77, 0xa3, 0xa7, 0x94, 0xf4, 0x69, 0x1d,
	0xbc, 0xfc, 0x08, 0x87, 0x5f, 0xf6, 0x98, 0x31, 0xd8, 0xd5, 0x7e, 0xf8, 0xe3, 0x52, 0x84, 0xf7,
	0x4d, 0xc3, 0x77, 0xb6, 0x1a, 0xde, 0x6e, 0x18, 0x7e, 0xf6, 0x4f, 0x1b, 0x8e, 0xde, 0x2b, 0x2d,
	0xb4, 0x54, 0x3a, 0x4f, 0xb0, 0x08, 0x33, 0xcb, 0x7e, 0x80, 0x5e, 0x11, 0x2e, 0x91, 0xaa, 0x7a,
	0xef, 0xba, 0x11, 0xb8, 0xc9, 0xd8, 0x6f, 0xd0, 0xad, 0x66, 0xc6, 0x14, 0x0a, 0x6d, 0x38, 0xa5,
	0x71, 0xf3, 0x8d, 0xc1, 0x4c, 0x56, 0x34, 0xf6, 0x3b, 0x00, 0x6a, 0x87, 0xd6, 0x58, 0x55, 0xc5,
	0xb5, 0xdc, 0x2a, 0x6a, 0x10, 0xd9, 0x5b, 0xe8, 0x4d, 0x85, 0x74, 0x64, 0x95, 0xce, 0xc3, 0xc6,
	0x6e, 0x55, 0xad, 0x79, 0xde, 0x99, 0xb0, 0x59, 0x7e, 0x87, 0xdb, 0x49, 0x78, 0x67, 0x97, 0x70,
	0x4c, 0x36, 0x43, 0x1b, 0xfb, 0x95, 0xa2, 0x96, 0x76, 0x61, 0x1c, 0xdf, 0x0b, 0x6b, 0xc5, 0xbe,
	0xee, 0x5b, 0x72, 0x14, 0xe8, 0xa1, 0x6d, 0xd7, 0x91, 0xcc, 0xde, 0x41, 0xbf, 0xf1, 0x8d, 0xb0,
	0xb8, 0x5b, 0x7b, 0x0e, 0x6b, 0x39, 0x7b, 0x0d, 0x9d, 0x07, 0xa1, 0x3f, 0x57, 0xbc, 0x1b, 0x14,
	0xc3, 0x5a, 0xe1, 0x87, 0xab, 0x4a, 0x62, 0xee, 0xec, 0x57, 0xe8, 0x84, 0x78, 0xcd, 0x6e, 0x85,
	0xda, 0x56, 0xec, 0x0b, 0x63, 0xfe, 0xa6, 0x9a, 0xfd, 0x6f, 0x0b, 0x0e, 0x3d, 0xfd, 0x96, 0x84,
	0x7e, 0x5e, 0xcf, 0x36, 0x9c, 0xdc, 0x79, 0xa6, 0x93, 0x13, 0xe8, 0xf9, 0xf3, 0xe2, 0xb0, 0x3e,
	0xd9, 0xb4, 0xae, 0xe7, 0xf9, 0x59, 0x5d, 0xb9, 0xbf, 0xdb, 0x70, 0xff, 0x0b, 0xe7, 0x3a, 0xcf,
	0x74, 0xee, 0xf2, 0x16, 0xde, 0x48, 0x2a, 0x47, 0x73, 0x25, 0x74, 0xae, 0xc5, 0xe8, 0xf1, 0xf1,
	0xb1, 0xd6, 0x6c, 0xfc, 0x62, 0x3e, 0xbe, 0xc9, 0x95, 0xfb, 0x34, 0x7b, 0x18, 0x49, 0x2a, 0xc7,
	0x73, 0x2d, 0xe5, 0x38, 0xb2, 0xc6, 0x1b, 0xac, 0x87, 0xf8, 0xdb, 0x79, 0xfb, 0x7f, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x0a, 0xfd, 0x83, 0x9a, 0xa0, 0x06, 0x00, 0x00,
}
