// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: contract/contract_request.proto

package com.xiangna.www.protos.contract;

public final class ContractRequest {
  private ContractRequest() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ContractExcuteRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protos.ContractExcuteRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 操作
     * </pre>
     *
     * <code>optional string action = 1;</code>
     */
    java.lang.String getAction();
    /**
     * <pre>
     * 操作
     * </pre>
     *
     * <code>optional string action = 1;</code>
     */
    com.google.protobuf.ByteString
        getActionBytes();

    /**
     * <pre>
     * 合约编号
     * </pre>
     *
     * <code>optional string no = 2;</code>
     */
    java.lang.String getNo();
    /**
     * <pre>
     * 合约编号
     * </pre>
     *
     * <code>optional string no = 2;</code>
     */
    com.google.protobuf.ByteString
        getNoBytes();

    /**
     * <pre>
     * 合约数据
     * </pre>
     *
     * <code>optional bytes contractData = 3;</code>
     */
    com.google.protobuf.ByteString getContractData();
  }
  /**
   * <pre>
   * 执行合约请求参数
   * </pre>
   *
   * Protobuf type {@code protos.ContractExcuteRequest}
   */
  public  static final class ContractExcuteRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protos.ContractExcuteRequest)
      ContractExcuteRequestOrBuilder {
    // Use ContractExcuteRequest.newBuilder() to construct.
    private ContractExcuteRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ContractExcuteRequest() {
      action_ = "";
      no_ = "";
      contractData_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private ContractExcuteRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              action_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              no_ = s;
              break;
            }
            case 26: {

              contractData_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.xiangna.www.protos.contract.ContractRequest.internal_static_protos_ContractExcuteRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.xiangna.www.protos.contract.ContractRequest.internal_static_protos_ContractExcuteRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.xiangna.www.protos.contract.ContractRequest.ContractExcuteRequest.class, com.xiangna.www.protos.contract.ContractRequest.ContractExcuteRequest.Builder.class);
    }

    public static final int ACTION_FIELD_NUMBER = 1;
    private volatile java.lang.Object action_;
    /**
     * <pre>
     * 操作
     * </pre>
     *
     * <code>optional string action = 1;</code>
     */
    public java.lang.String getAction() {
      java.lang.Object ref = action_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        action_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 操作
     * </pre>
     *
     * <code>optional string action = 1;</code>
     */
    public com.google.protobuf.ByteString
        getActionBytes() {
      java.lang.Object ref = action_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        action_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NO_FIELD_NUMBER = 2;
    private volatile java.lang.Object no_;
    /**
     * <pre>
     * 合约编号
     * </pre>
     *
     * <code>optional string no = 2;</code>
     */
    public java.lang.String getNo() {
      java.lang.Object ref = no_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        no_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 合约编号
     * </pre>
     *
     * <code>optional string no = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNoBytes() {
      java.lang.Object ref = no_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        no_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CONTRACTDATA_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString contractData_;
    /**
     * <pre>
     * 合约数据
     * </pre>
     *
     * <code>optional bytes contractData = 3;</code>
     */
    public com.google.protobuf.ByteString getContractData() {
      return contractData_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getActionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, action_);
      }
      if (!getNoBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, no_);
      }
      if (!contractData_.isEmpty()) {
        output.writeBytes(3, contractData_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getActionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, action_);
      }
      if (!getNoBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, no_);
      }
      if (!contractData_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, contractData_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.xiangna.www.protos.contract.ContractRequest.ContractExcuteRequest)) {
        return super.equals(obj);
      }
      com.xiangna.www.protos.contract.ContractRequest.ContractExcuteRequest other = (com.xiangna.www.protos.contract.ContractRequest.ContractExcuteRequest) obj;

      boolean result = true;
      result = result && getAction()
          .equals(other.getAction());
      result = result && getNo()
          .equals(other.getNo());
      result = result && getContractData()
          .equals(other.getContractData());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + ACTION_FIELD_NUMBER;
      hash = (53 * hash) + getAction().hashCode();
      hash = (37 * hash) + NO_FIELD_NUMBER;
      hash = (53 * hash) + getNo().hashCode();
      hash = (37 * hash) + CONTRACTDATA_FIELD_NUMBER;
      hash = (53 * hash) + getContractData().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.xiangna.www.protos.contract.ContractRequest.ContractExcuteRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xiangna.www.protos.contract.ContractRequest.ContractExcuteRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xiangna.www.protos.contract.ContractRequest.ContractExcuteRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xiangna.www.protos.contract.ContractRequest.ContractExcuteRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xiangna.www.protos.contract.ContractRequest.ContractExcuteRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.xiangna.www.protos.contract.ContractRequest.ContractExcuteRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.xiangna.www.protos.contract.ContractRequest.ContractExcuteRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.xiangna.www.protos.contract.ContractRequest.ContractExcuteRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.xiangna.www.protos.contract.ContractRequest.ContractExcuteRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.xiangna.www.protos.contract.ContractRequest.ContractExcuteRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.xiangna.www.protos.contract.ContractRequest.ContractExcuteRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 执行合约请求参数
     * </pre>
     *
     * Protobuf type {@code protos.ContractExcuteRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protos.ContractExcuteRequest)
        com.xiangna.www.protos.contract.ContractRequest.ContractExcuteRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.xiangna.www.protos.contract.ContractRequest.internal_static_protos_ContractExcuteRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.xiangna.www.protos.contract.ContractRequest.internal_static_protos_ContractExcuteRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.xiangna.www.protos.contract.ContractRequest.ContractExcuteRequest.class, com.xiangna.www.protos.contract.ContractRequest.ContractExcuteRequest.Builder.class);
      }

      // Construct using com.xiangna.www.protos.contract.ContractRequest.ContractExcuteRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        action_ = "";

        no_ = "";

        contractData_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.xiangna.www.protos.contract.ContractRequest.internal_static_protos_ContractExcuteRequest_descriptor;
      }

      public com.xiangna.www.protos.contract.ContractRequest.ContractExcuteRequest getDefaultInstanceForType() {
        return com.xiangna.www.protos.contract.ContractRequest.ContractExcuteRequest.getDefaultInstance();
      }

      public com.xiangna.www.protos.contract.ContractRequest.ContractExcuteRequest build() {
        com.xiangna.www.protos.contract.ContractRequest.ContractExcuteRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.xiangna.www.protos.contract.ContractRequest.ContractExcuteRequest buildPartial() {
        com.xiangna.www.protos.contract.ContractRequest.ContractExcuteRequest result = new com.xiangna.www.protos.contract.ContractRequest.ContractExcuteRequest(this);
        result.action_ = action_;
        result.no_ = no_;
        result.contractData_ = contractData_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.xiangna.www.protos.contract.ContractRequest.ContractExcuteRequest) {
          return mergeFrom((com.xiangna.www.protos.contract.ContractRequest.ContractExcuteRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.xiangna.www.protos.contract.ContractRequest.ContractExcuteRequest other) {
        if (other == com.xiangna.www.protos.contract.ContractRequest.ContractExcuteRequest.getDefaultInstance()) return this;
        if (!other.getAction().isEmpty()) {
          action_ = other.action_;
          onChanged();
        }
        if (!other.getNo().isEmpty()) {
          no_ = other.no_;
          onChanged();
        }
        if (other.getContractData() != com.google.protobuf.ByteString.EMPTY) {
          setContractData(other.getContractData());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.xiangna.www.protos.contract.ContractRequest.ContractExcuteRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.xiangna.www.protos.contract.ContractRequest.ContractExcuteRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object action_ = "";
      /**
       * <pre>
       * 操作
       * </pre>
       *
       * <code>optional string action = 1;</code>
       */
      public java.lang.String getAction() {
        java.lang.Object ref = action_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          action_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 操作
       * </pre>
       *
       * <code>optional string action = 1;</code>
       */
      public com.google.protobuf.ByteString
          getActionBytes() {
        java.lang.Object ref = action_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          action_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 操作
       * </pre>
       *
       * <code>optional string action = 1;</code>
       */
      public Builder setAction(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        action_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 操作
       * </pre>
       *
       * <code>optional string action = 1;</code>
       */
      public Builder clearAction() {
        
        action_ = getDefaultInstance().getAction();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 操作
       * </pre>
       *
       * <code>optional string action = 1;</code>
       */
      public Builder setActionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        action_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object no_ = "";
      /**
       * <pre>
       * 合约编号
       * </pre>
       *
       * <code>optional string no = 2;</code>
       */
      public java.lang.String getNo() {
        java.lang.Object ref = no_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          no_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 合约编号
       * </pre>
       *
       * <code>optional string no = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNoBytes() {
        java.lang.Object ref = no_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          no_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 合约编号
       * </pre>
       *
       * <code>optional string no = 2;</code>
       */
      public Builder setNo(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        no_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 合约编号
       * </pre>
       *
       * <code>optional string no = 2;</code>
       */
      public Builder clearNo() {
        
        no_ = getDefaultInstance().getNo();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 合约编号
       * </pre>
       *
       * <code>optional string no = 2;</code>
       */
      public Builder setNoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        no_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString contractData_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * 合约数据
       * </pre>
       *
       * <code>optional bytes contractData = 3;</code>
       */
      public com.google.protobuf.ByteString getContractData() {
        return contractData_;
      }
      /**
       * <pre>
       * 合约数据
       * </pre>
       *
       * <code>optional bytes contractData = 3;</code>
       */
      public Builder setContractData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        contractData_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 合约数据
       * </pre>
       *
       * <code>optional bytes contractData = 3;</code>
       */
      public Builder clearContractData() {
        
        contractData_ = getDefaultInstance().getContractData();
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:protos.ContractExcuteRequest)
    }

    // @@protoc_insertion_point(class_scope:protos.ContractExcuteRequest)
    private static final com.xiangna.www.protos.contract.ContractRequest.ContractExcuteRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.xiangna.www.protos.contract.ContractRequest.ContractExcuteRequest();
    }

    public static com.xiangna.www.protos.contract.ContractRequest.ContractExcuteRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ContractExcuteRequest>
        PARSER = new com.google.protobuf.AbstractParser<ContractExcuteRequest>() {
      public ContractExcuteRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ContractExcuteRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ContractExcuteRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ContractExcuteRequest> getParserForType() {
      return PARSER;
    }

    public com.xiangna.www.protos.contract.ContractRequest.ContractExcuteRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ContractAddCheckLogRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protos.ContractAddCheckLogRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 合约编号
     * </pre>
     *
     * <code>optional string no = 1;</code>
     */
    java.lang.String getNo();
    /**
     * <pre>
     * 合约编号
     * </pre>
     *
     * <code>optional string no = 1;</code>
     */
    com.google.protobuf.ByteString
        getNoBytes();

    /**
     * <pre>
     * refer message contract.ContractCheckFlowData
     * </pre>
     *
     * <code>optional bytes contractCheckFlowData = 2;</code>
     */
    com.google.protobuf.ByteString getContractCheckFlowData();
  }
  /**
   * <pre>
   * 合约新增审批日志请求参数
   * </pre>
   *
   * Protobuf type {@code protos.ContractAddCheckLogRequest}
   */
  public  static final class ContractAddCheckLogRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protos.ContractAddCheckLogRequest)
      ContractAddCheckLogRequestOrBuilder {
    // Use ContractAddCheckLogRequest.newBuilder() to construct.
    private ContractAddCheckLogRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ContractAddCheckLogRequest() {
      no_ = "";
      contractCheckFlowData_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private ContractAddCheckLogRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              no_ = s;
              break;
            }
            case 18: {

              contractCheckFlowData_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.xiangna.www.protos.contract.ContractRequest.internal_static_protos_ContractAddCheckLogRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.xiangna.www.protos.contract.ContractRequest.internal_static_protos_ContractAddCheckLogRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.xiangna.www.protos.contract.ContractRequest.ContractAddCheckLogRequest.class, com.xiangna.www.protos.contract.ContractRequest.ContractAddCheckLogRequest.Builder.class);
    }

    public static final int NO_FIELD_NUMBER = 1;
    private volatile java.lang.Object no_;
    /**
     * <pre>
     * 合约编号
     * </pre>
     *
     * <code>optional string no = 1;</code>
     */
    public java.lang.String getNo() {
      java.lang.Object ref = no_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        no_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 合约编号
     * </pre>
     *
     * <code>optional string no = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNoBytes() {
      java.lang.Object ref = no_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        no_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CONTRACTCHECKFLOWDATA_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString contractCheckFlowData_;
    /**
     * <pre>
     * refer message contract.ContractCheckFlowData
     * </pre>
     *
     * <code>optional bytes contractCheckFlowData = 2;</code>
     */
    public com.google.protobuf.ByteString getContractCheckFlowData() {
      return contractCheckFlowData_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNoBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, no_);
      }
      if (!contractCheckFlowData_.isEmpty()) {
        output.writeBytes(2, contractCheckFlowData_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNoBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, no_);
      }
      if (!contractCheckFlowData_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, contractCheckFlowData_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.xiangna.www.protos.contract.ContractRequest.ContractAddCheckLogRequest)) {
        return super.equals(obj);
      }
      com.xiangna.www.protos.contract.ContractRequest.ContractAddCheckLogRequest other = (com.xiangna.www.protos.contract.ContractRequest.ContractAddCheckLogRequest) obj;

      boolean result = true;
      result = result && getNo()
          .equals(other.getNo());
      result = result && getContractCheckFlowData()
          .equals(other.getContractCheckFlowData());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + NO_FIELD_NUMBER;
      hash = (53 * hash) + getNo().hashCode();
      hash = (37 * hash) + CONTRACTCHECKFLOWDATA_FIELD_NUMBER;
      hash = (53 * hash) + getContractCheckFlowData().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.xiangna.www.protos.contract.ContractRequest.ContractAddCheckLogRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xiangna.www.protos.contract.ContractRequest.ContractAddCheckLogRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xiangna.www.protos.contract.ContractRequest.ContractAddCheckLogRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xiangna.www.protos.contract.ContractRequest.ContractAddCheckLogRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xiangna.www.protos.contract.ContractRequest.ContractAddCheckLogRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.xiangna.www.protos.contract.ContractRequest.ContractAddCheckLogRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.xiangna.www.protos.contract.ContractRequest.ContractAddCheckLogRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.xiangna.www.protos.contract.ContractRequest.ContractAddCheckLogRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.xiangna.www.protos.contract.ContractRequest.ContractAddCheckLogRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.xiangna.www.protos.contract.ContractRequest.ContractAddCheckLogRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.xiangna.www.protos.contract.ContractRequest.ContractAddCheckLogRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 合约新增审批日志请求参数
     * </pre>
     *
     * Protobuf type {@code protos.ContractAddCheckLogRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protos.ContractAddCheckLogRequest)
        com.xiangna.www.protos.contract.ContractRequest.ContractAddCheckLogRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.xiangna.www.protos.contract.ContractRequest.internal_static_protos_ContractAddCheckLogRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.xiangna.www.protos.contract.ContractRequest.internal_static_protos_ContractAddCheckLogRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.xiangna.www.protos.contract.ContractRequest.ContractAddCheckLogRequest.class, com.xiangna.www.protos.contract.ContractRequest.ContractAddCheckLogRequest.Builder.class);
      }

      // Construct using com.xiangna.www.protos.contract.ContractRequest.ContractAddCheckLogRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        no_ = "";

        contractCheckFlowData_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.xiangna.www.protos.contract.ContractRequest.internal_static_protos_ContractAddCheckLogRequest_descriptor;
      }

      public com.xiangna.www.protos.contract.ContractRequest.ContractAddCheckLogRequest getDefaultInstanceForType() {
        return com.xiangna.www.protos.contract.ContractRequest.ContractAddCheckLogRequest.getDefaultInstance();
      }

      public com.xiangna.www.protos.contract.ContractRequest.ContractAddCheckLogRequest build() {
        com.xiangna.www.protos.contract.ContractRequest.ContractAddCheckLogRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.xiangna.www.protos.contract.ContractRequest.ContractAddCheckLogRequest buildPartial() {
        com.xiangna.www.protos.contract.ContractRequest.ContractAddCheckLogRequest result = new com.xiangna.www.protos.contract.ContractRequest.ContractAddCheckLogRequest(this);
        result.no_ = no_;
        result.contractCheckFlowData_ = contractCheckFlowData_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.xiangna.www.protos.contract.ContractRequest.ContractAddCheckLogRequest) {
          return mergeFrom((com.xiangna.www.protos.contract.ContractRequest.ContractAddCheckLogRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.xiangna.www.protos.contract.ContractRequest.ContractAddCheckLogRequest other) {
        if (other == com.xiangna.www.protos.contract.ContractRequest.ContractAddCheckLogRequest.getDefaultInstance()) return this;
        if (!other.getNo().isEmpty()) {
          no_ = other.no_;
          onChanged();
        }
        if (other.getContractCheckFlowData() != com.google.protobuf.ByteString.EMPTY) {
          setContractCheckFlowData(other.getContractCheckFlowData());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.xiangna.www.protos.contract.ContractRequest.ContractAddCheckLogRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.xiangna.www.protos.contract.ContractRequest.ContractAddCheckLogRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object no_ = "";
      /**
       * <pre>
       * 合约编号
       * </pre>
       *
       * <code>optional string no = 1;</code>
       */
      public java.lang.String getNo() {
        java.lang.Object ref = no_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          no_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 合约编号
       * </pre>
       *
       * <code>optional string no = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNoBytes() {
        java.lang.Object ref = no_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          no_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 合约编号
       * </pre>
       *
       * <code>optional string no = 1;</code>
       */
      public Builder setNo(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        no_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 合约编号
       * </pre>
       *
       * <code>optional string no = 1;</code>
       */
      public Builder clearNo() {
        
        no_ = getDefaultInstance().getNo();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 合约编号
       * </pre>
       *
       * <code>optional string no = 1;</code>
       */
      public Builder setNoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        no_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString contractCheckFlowData_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * refer message contract.ContractCheckFlowData
       * </pre>
       *
       * <code>optional bytes contractCheckFlowData = 2;</code>
       */
      public com.google.protobuf.ByteString getContractCheckFlowData() {
        return contractCheckFlowData_;
      }
      /**
       * <pre>
       * refer message contract.ContractCheckFlowData
       * </pre>
       *
       * <code>optional bytes contractCheckFlowData = 2;</code>
       */
      public Builder setContractCheckFlowData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        contractCheckFlowData_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * refer message contract.ContractCheckFlowData
       * </pre>
       *
       * <code>optional bytes contractCheckFlowData = 2;</code>
       */
      public Builder clearContractCheckFlowData() {
        
        contractCheckFlowData_ = getDefaultInstance().getContractCheckFlowData();
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:protos.ContractAddCheckLogRequest)
    }

    // @@protoc_insertion_point(class_scope:protos.ContractAddCheckLogRequest)
    private static final com.xiangna.www.protos.contract.ContractRequest.ContractAddCheckLogRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.xiangna.www.protos.contract.ContractRequest.ContractAddCheckLogRequest();
    }

    public static com.xiangna.www.protos.contract.ContractRequest.ContractAddCheckLogRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ContractAddCheckLogRequest>
        PARSER = new com.google.protobuf.AbstractParser<ContractAddCheckLogRequest>() {
      public ContractAddCheckLogRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ContractAddCheckLogRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ContractAddCheckLogRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ContractAddCheckLogRequest> getParserForType() {
      return PARSER;
    }

    public com.xiangna.www.protos.contract.ContractRequest.ContractAddCheckLogRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ContractQueryRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protos.ContractQueryRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 合约编号
     * </pre>
     *
     * <code>optional string no = 1;</code>
     */
    java.lang.String getNo();
    /**
     * <pre>
     * 合约编号
     * </pre>
     *
     * <code>optional string no = 1;</code>
     */
    com.google.protobuf.ByteString
        getNoBytes();

    /**
     * <code>optional .protos.ContractQueryRequest.QueryType type = 2;</code>
     */
    int getTypeValue();
    /**
     * <code>optional .protos.ContractQueryRequest.QueryType type = 2;</code>
     */
    com.xiangna.www.protos.contract.ContractRequest.ContractQueryRequest.QueryType getType();

    /**
     * <pre>
     * 查询文件的key
     * </pre>
     *
     * <code>optional string fileKey = 3;</code>
     */
    java.lang.String getFileKey();
    /**
     * <pre>
     * 查询文件的key
     * </pre>
     *
     * <code>optional string fileKey = 3;</code>
     */
    com.google.protobuf.ByteString
        getFileKeyBytes();
  }
  /**
   * <pre>
   * 合约查询请求参数
   * </pre>
   *
   * Protobuf type {@code protos.ContractQueryRequest}
   */
  public  static final class ContractQueryRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protos.ContractQueryRequest)
      ContractQueryRequestOrBuilder {
    // Use ContractQueryRequest.newBuilder() to construct.
    private ContractQueryRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ContractQueryRequest() {
      no_ = "";
      type_ = 0;
      fileKey_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private ContractQueryRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              no_ = s;
              break;
            }
            case 16: {
              int rawValue = input.readEnum();

              type_ = rawValue;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              fileKey_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.xiangna.www.protos.contract.ContractRequest.internal_static_protos_ContractQueryRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.xiangna.www.protos.contract.ContractRequest.internal_static_protos_ContractQueryRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.xiangna.www.protos.contract.ContractRequest.ContractQueryRequest.class, com.xiangna.www.protos.contract.ContractRequest.ContractQueryRequest.Builder.class);
    }

    /**
     * <pre>
     * 查询类型
     * </pre>
     *
     * Protobuf enum {@code protos.ContractQueryRequest.QueryType}
     */
    public enum QueryType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <pre>
       * 查询所有合约数据
       * </pre>
       *
       * <code>ALL = 0;</code>
       */
      ALL(0),
      /**
       * <pre>
       * 查询具体的文件详情(返回文件流)
       * </pre>
       *
       * <code>FILE = 1;</code>
       */
      FILE(1),
      /**
       * <pre>
       * 查询合约的文件列表(不包含文件流)
       * </pre>
       *
       * <code>FILELILST = 2;</code>
       */
      FILELILST(2),
      UNRECOGNIZED(-1),
      ;

      /**
       * <pre>
       * 查询所有合约数据
       * </pre>
       *
       * <code>ALL = 0;</code>
       */
      public static final int ALL_VALUE = 0;
      /**
       * <pre>
       * 查询具体的文件详情(返回文件流)
       * </pre>
       *
       * <code>FILE = 1;</code>
       */
      public static final int FILE_VALUE = 1;
      /**
       * <pre>
       * 查询合约的文件列表(不包含文件流)
       * </pre>
       *
       * <code>FILELILST = 2;</code>
       */
      public static final int FILELILST_VALUE = 2;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static QueryType valueOf(int value) {
        return forNumber(value);
      }

      public static QueryType forNumber(int value) {
        switch (value) {
          case 0: return ALL;
          case 1: return FILE;
          case 2: return FILELILST;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<QueryType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          QueryType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<QueryType>() {
              public QueryType findValueByNumber(int number) {
                return QueryType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.xiangna.www.protos.contract.ContractRequest.ContractQueryRequest.getDescriptor().getEnumTypes().get(0);
      }

      private static final QueryType[] VALUES = values();

      public static QueryType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private QueryType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:protos.ContractQueryRequest.QueryType)
    }

    public static final int NO_FIELD_NUMBER = 1;
    private volatile java.lang.Object no_;
    /**
     * <pre>
     * 合约编号
     * </pre>
     *
     * <code>optional string no = 1;</code>
     */
    public java.lang.String getNo() {
      java.lang.Object ref = no_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        no_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 合约编号
     * </pre>
     *
     * <code>optional string no = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNoBytes() {
      java.lang.Object ref = no_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        no_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TYPE_FIELD_NUMBER = 2;
    private int type_;
    /**
     * <code>optional .protos.ContractQueryRequest.QueryType type = 2;</code>
     */
    public int getTypeValue() {
      return type_;
    }
    /**
     * <code>optional .protos.ContractQueryRequest.QueryType type = 2;</code>
     */
    public com.xiangna.www.protos.contract.ContractRequest.ContractQueryRequest.QueryType getType() {
      com.xiangna.www.protos.contract.ContractRequest.ContractQueryRequest.QueryType result = com.xiangna.www.protos.contract.ContractRequest.ContractQueryRequest.QueryType.valueOf(type_);
      return result == null ? com.xiangna.www.protos.contract.ContractRequest.ContractQueryRequest.QueryType.UNRECOGNIZED : result;
    }

    public static final int FILEKEY_FIELD_NUMBER = 3;
    private volatile java.lang.Object fileKey_;
    /**
     * <pre>
     * 查询文件的key
     * </pre>
     *
     * <code>optional string fileKey = 3;</code>
     */
    public java.lang.String getFileKey() {
      java.lang.Object ref = fileKey_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        fileKey_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 查询文件的key
     * </pre>
     *
     * <code>optional string fileKey = 3;</code>
     */
    public com.google.protobuf.ByteString
        getFileKeyBytes() {
      java.lang.Object ref = fileKey_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fileKey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNoBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, no_);
      }
      if (type_ != com.xiangna.www.protos.contract.ContractRequest.ContractQueryRequest.QueryType.ALL.getNumber()) {
        output.writeEnum(2, type_);
      }
      if (!getFileKeyBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, fileKey_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNoBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, no_);
      }
      if (type_ != com.xiangna.www.protos.contract.ContractRequest.ContractQueryRequest.QueryType.ALL.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, type_);
      }
      if (!getFileKeyBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, fileKey_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.xiangna.www.protos.contract.ContractRequest.ContractQueryRequest)) {
        return super.equals(obj);
      }
      com.xiangna.www.protos.contract.ContractRequest.ContractQueryRequest other = (com.xiangna.www.protos.contract.ContractRequest.ContractQueryRequest) obj;

      boolean result = true;
      result = result && getNo()
          .equals(other.getNo());
      result = result && type_ == other.type_;
      result = result && getFileKey()
          .equals(other.getFileKey());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + NO_FIELD_NUMBER;
      hash = (53 * hash) + getNo().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      hash = (37 * hash) + FILEKEY_FIELD_NUMBER;
      hash = (53 * hash) + getFileKey().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.xiangna.www.protos.contract.ContractRequest.ContractQueryRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xiangna.www.protos.contract.ContractRequest.ContractQueryRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xiangna.www.protos.contract.ContractRequest.ContractQueryRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xiangna.www.protos.contract.ContractRequest.ContractQueryRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xiangna.www.protos.contract.ContractRequest.ContractQueryRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.xiangna.www.protos.contract.ContractRequest.ContractQueryRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.xiangna.www.protos.contract.ContractRequest.ContractQueryRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.xiangna.www.protos.contract.ContractRequest.ContractQueryRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.xiangna.www.protos.contract.ContractRequest.ContractQueryRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.xiangna.www.protos.contract.ContractRequest.ContractQueryRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.xiangna.www.protos.contract.ContractRequest.ContractQueryRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 合约查询请求参数
     * </pre>
     *
     * Protobuf type {@code protos.ContractQueryRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protos.ContractQueryRequest)
        com.xiangna.www.protos.contract.ContractRequest.ContractQueryRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.xiangna.www.protos.contract.ContractRequest.internal_static_protos_ContractQueryRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.xiangna.www.protos.contract.ContractRequest.internal_static_protos_ContractQueryRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.xiangna.www.protos.contract.ContractRequest.ContractQueryRequest.class, com.xiangna.www.protos.contract.ContractRequest.ContractQueryRequest.Builder.class);
      }

      // Construct using com.xiangna.www.protos.contract.ContractRequest.ContractQueryRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        no_ = "";

        type_ = 0;

        fileKey_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.xiangna.www.protos.contract.ContractRequest.internal_static_protos_ContractQueryRequest_descriptor;
      }

      public com.xiangna.www.protos.contract.ContractRequest.ContractQueryRequest getDefaultInstanceForType() {
        return com.xiangna.www.protos.contract.ContractRequest.ContractQueryRequest.getDefaultInstance();
      }

      public com.xiangna.www.protos.contract.ContractRequest.ContractQueryRequest build() {
        com.xiangna.www.protos.contract.ContractRequest.ContractQueryRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.xiangna.www.protos.contract.ContractRequest.ContractQueryRequest buildPartial() {
        com.xiangna.www.protos.contract.ContractRequest.ContractQueryRequest result = new com.xiangna.www.protos.contract.ContractRequest.ContractQueryRequest(this);
        result.no_ = no_;
        result.type_ = type_;
        result.fileKey_ = fileKey_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.xiangna.www.protos.contract.ContractRequest.ContractQueryRequest) {
          return mergeFrom((com.xiangna.www.protos.contract.ContractRequest.ContractQueryRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.xiangna.www.protos.contract.ContractRequest.ContractQueryRequest other) {
        if (other == com.xiangna.www.protos.contract.ContractRequest.ContractQueryRequest.getDefaultInstance()) return this;
        if (!other.getNo().isEmpty()) {
          no_ = other.no_;
          onChanged();
        }
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        if (!other.getFileKey().isEmpty()) {
          fileKey_ = other.fileKey_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.xiangna.www.protos.contract.ContractRequest.ContractQueryRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.xiangna.www.protos.contract.ContractRequest.ContractQueryRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object no_ = "";
      /**
       * <pre>
       * 合约编号
       * </pre>
       *
       * <code>optional string no = 1;</code>
       */
      public java.lang.String getNo() {
        java.lang.Object ref = no_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          no_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 合约编号
       * </pre>
       *
       * <code>optional string no = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNoBytes() {
        java.lang.Object ref = no_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          no_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 合约编号
       * </pre>
       *
       * <code>optional string no = 1;</code>
       */
      public Builder setNo(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        no_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 合约编号
       * </pre>
       *
       * <code>optional string no = 1;</code>
       */
      public Builder clearNo() {
        
        no_ = getDefaultInstance().getNo();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 合约编号
       * </pre>
       *
       * <code>optional string no = 1;</code>
       */
      public Builder setNoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        no_ = value;
        onChanged();
        return this;
      }

      private int type_ = 0;
      /**
       * <code>optional .protos.ContractQueryRequest.QueryType type = 2;</code>
       */
      public int getTypeValue() {
        return type_;
      }
      /**
       * <code>optional .protos.ContractQueryRequest.QueryType type = 2;</code>
       */
      public Builder setTypeValue(int value) {
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .protos.ContractQueryRequest.QueryType type = 2;</code>
       */
      public com.xiangna.www.protos.contract.ContractRequest.ContractQueryRequest.QueryType getType() {
        com.xiangna.www.protos.contract.ContractRequest.ContractQueryRequest.QueryType result = com.xiangna.www.protos.contract.ContractRequest.ContractQueryRequest.QueryType.valueOf(type_);
        return result == null ? com.xiangna.www.protos.contract.ContractRequest.ContractQueryRequest.QueryType.UNRECOGNIZED : result;
      }
      /**
       * <code>optional .protos.ContractQueryRequest.QueryType type = 2;</code>
       */
      public Builder setType(com.xiangna.www.protos.contract.ContractRequest.ContractQueryRequest.QueryType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .protos.ContractQueryRequest.QueryType type = 2;</code>
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object fileKey_ = "";
      /**
       * <pre>
       * 查询文件的key
       * </pre>
       *
       * <code>optional string fileKey = 3;</code>
       */
      public java.lang.String getFileKey() {
        java.lang.Object ref = fileKey_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          fileKey_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 查询文件的key
       * </pre>
       *
       * <code>optional string fileKey = 3;</code>
       */
      public com.google.protobuf.ByteString
          getFileKeyBytes() {
        java.lang.Object ref = fileKey_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          fileKey_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 查询文件的key
       * </pre>
       *
       * <code>optional string fileKey = 3;</code>
       */
      public Builder setFileKey(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        fileKey_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 查询文件的key
       * </pre>
       *
       * <code>optional string fileKey = 3;</code>
       */
      public Builder clearFileKey() {
        
        fileKey_ = getDefaultInstance().getFileKey();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 查询文件的key
       * </pre>
       *
       * <code>optional string fileKey = 3;</code>
       */
      public Builder setFileKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        fileKey_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:protos.ContractQueryRequest)
    }

    // @@protoc_insertion_point(class_scope:protos.ContractQueryRequest)
    private static final com.xiangna.www.protos.contract.ContractRequest.ContractQueryRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.xiangna.www.protos.contract.ContractRequest.ContractQueryRequest();
    }

    public static com.xiangna.www.protos.contract.ContractRequest.ContractQueryRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ContractQueryRequest>
        PARSER = new com.google.protobuf.AbstractParser<ContractQueryRequest>() {
      public ContractQueryRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ContractQueryRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ContractQueryRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ContractQueryRequest> getParserForType() {
      return PARSER;
    }

    public com.xiangna.www.protos.contract.ContractRequest.ContractQueryRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protos_ContractExcuteRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protos_ContractExcuteRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protos_ContractAddCheckLogRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protos_ContractAddCheckLogRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protos_ContractQueryRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protos_ContractQueryRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\037contract/contract_request.proto\022\006proto" +
      "s\"I\n\025ContractExcuteRequest\022\016\n\006action\030\001 \001" +
      "(\t\022\n\n\002no\030\002 \001(\t\022\024\n\014contractData\030\003 \001(\014\"G\n\032" +
      "ContractAddCheckLogRequest\022\n\n\002no\030\001 \001(\t\022\035" +
      "\n\025contractCheckFlowData\030\002 \001(\014\"\230\001\n\024Contra" +
      "ctQueryRequest\022\n\n\002no\030\001 \001(\t\0224\n\004type\030\002 \001(\016" +
      "2&.protos.ContractQueryRequest.QueryType" +
      "\022\017\n\007fileKey\030\003 \001(\t\"-\n\tQueryType\022\007\n\003ALL\020\000\022" +
      "\010\n\004FILE\020\001\022\r\n\tFILELILST\020\002BB\n\037com.xiangna." +
      "www.protos.contractZ\037github.com/xncc/pro",
      "tos/contractb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_protos_ContractExcuteRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protos_ContractExcuteRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protos_ContractExcuteRequest_descriptor,
        new java.lang.String[] { "Action", "No", "ContractData", });
    internal_static_protos_ContractAddCheckLogRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_protos_ContractAddCheckLogRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protos_ContractAddCheckLogRequest_descriptor,
        new java.lang.String[] { "No", "ContractCheckFlowData", });
    internal_static_protos_ContractQueryRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_protos_ContractQueryRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protos_ContractQueryRequest_descriptor,
        new java.lang.String[] { "No", "Type", "FileKey", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
