// Code generated by protoc-gen-go.
// source: financingorder/common.proto
// DO NOT EDIT!

/*
Package financingorder is a generated protocol buffer package.

It is generated from these files:
	financingorder/common.proto
	financingorder/configuration.proto
	financingorder/ledger_order.proto

It has these top-level messages:
	AppVo
	OperateInfo
	LedgerFile
	OrgBankAccount
	APPConfigBrief
	APPConfig
	NodeConfig
	CommercialOrg
	FinancingRelation
	BankLoanRelation
	FinancingOrderStep
	FinancingOrderStepFlow
	FinancingOrder
	OrderFormData
	FinancingInvoice
	Invoice
	OrderMoneyCount
	OrderTransactionDetail
	OrderStatus
	BankLoanOrder
	FinancingOrderReview
	OrderCheckFlowInfo
	OrderCheckFlowData
	OrderStepCheckData
	CheckData
*/
package financingorder

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// 机构摘要
type AppVo struct {
	AppId   string `protobuf:"bytes,1,opt,name=appId" json:"appId,omitempty"`
	AppName string `protobuf:"bytes,2,opt,name=appName" json:"appName,omitempty"`
	Type    string `protobuf:"bytes,3,opt,name=type" json:"type,omitempty"`
}

func (m *AppVo) Reset()                    { *m = AppVo{} }
func (m *AppVo) String() string            { return proto.CompactTextString(m) }
func (*AppVo) ProtoMessage()               {}
func (*AppVo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *AppVo) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *AppVo) GetAppName() string {
	if m != nil {
		return m.AppName
	}
	return ""
}

func (m *AppVo) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

// 数据操作信息
type OperateInfo struct {
	// 创建操作信息
	Creater    *AppVo                     `protobuf:"bytes,1,opt,name=creater" json:"creater,omitempty"`
	CreateTime *google_protobuf.Timestamp `protobuf:"bytes,2,opt,name=create_time,json=createTime" json:"create_time,omitempty"`
	CreaterIp  string                     `protobuf:"bytes,3,opt,name=creater_ip,json=createrIp" json:"creater_ip,omitempty"`
	// 更新操作信息
	LastUser *AppVo                     `protobuf:"bytes,4,opt,name=last_user,json=lastUser" json:"last_user,omitempty"`
	LastTime *google_protobuf.Timestamp `protobuf:"bytes,5,opt,name=last_time,json=lastTime" json:"last_time,omitempty"`
	LastIp   string                     `protobuf:"bytes,6,opt,name=last_ip,json=lastIp" json:"last_ip,omitempty"`
}

func (m *OperateInfo) Reset()                    { *m = OperateInfo{} }
func (m *OperateInfo) String() string            { return proto.CompactTextString(m) }
func (*OperateInfo) ProtoMessage()               {}
func (*OperateInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *OperateInfo) GetCreater() *AppVo {
	if m != nil {
		return m.Creater
	}
	return nil
}

func (m *OperateInfo) GetCreateTime() *google_protobuf.Timestamp {
	if m != nil {
		return m.CreateTime
	}
	return nil
}

func (m *OperateInfo) GetCreaterIp() string {
	if m != nil {
		return m.CreaterIp
	}
	return ""
}

func (m *OperateInfo) GetLastUser() *AppVo {
	if m != nil {
		return m.LastUser
	}
	return nil
}

func (m *OperateInfo) GetLastTime() *google_protobuf.Timestamp {
	if m != nil {
		return m.LastTime
	}
	return nil
}

func (m *OperateInfo) GetLastIp() string {
	if m != nil {
		return m.LastIp
	}
	return ""
}

// 账本链上文件
type LedgerFile struct {
	Url         string       `protobuf:"bytes,1,opt,name=url" json:"url,omitempty"`
	Data        []byte       `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Sha256      string       `protobuf:"bytes,3,opt,name=sha256" json:"sha256,omitempty"`
	Name        string       `protobuf:"bytes,4,opt,name=name" json:"name,omitempty"`
	Size        int64        `protobuf:"varint,5,opt,name=size" json:"size,omitempty"`
	Type        string       `protobuf:"bytes,6,opt,name=type" json:"type,omitempty"`
	OperateInfo *OperateInfo `protobuf:"bytes,7,opt,name=operate_info,json=operateInfo" json:"operate_info,omitempty"`
}

func (m *LedgerFile) Reset()                    { *m = LedgerFile{} }
func (m *LedgerFile) String() string            { return proto.CompactTextString(m) }
func (*LedgerFile) ProtoMessage()               {}
func (*LedgerFile) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *LedgerFile) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *LedgerFile) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *LedgerFile) GetSha256() string {
	if m != nil {
		return m.Sha256
	}
	return ""
}

func (m *LedgerFile) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *LedgerFile) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *LedgerFile) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *LedgerFile) GetOperateInfo() *OperateInfo {
	if m != nil {
		return m.OperateInfo
	}
	return nil
}

// 银行账户信息
type OrgBankAccount struct {
	Account    string `protobuf:"bytes,1,opt,name=account" json:"account,omitempty"`
	BankName   string `protobuf:"bytes,2,opt,name=bank_name,json=bankName" json:"bank_name,omitempty"`
	BankBranch string `protobuf:"bytes,3,opt,name=bank_branch,json=bankBranch" json:"bank_branch,omitempty"`
}

func (m *OrgBankAccount) Reset()                    { *m = OrgBankAccount{} }
func (m *OrgBankAccount) String() string            { return proto.CompactTextString(m) }
func (*OrgBankAccount) ProtoMessage()               {}
func (*OrgBankAccount) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *OrgBankAccount) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *OrgBankAccount) GetBankName() string {
	if m != nil {
		return m.BankName
	}
	return ""
}

func (m *OrgBankAccount) GetBankBranch() string {
	if m != nil {
		return m.BankBranch
	}
	return ""
}

func init() {
	proto.RegisterType((*AppVo)(nil), "protos.AppVo")
	proto.RegisterType((*OperateInfo)(nil), "protos.OperateInfo")
	proto.RegisterType((*LedgerFile)(nil), "protos.LedgerFile")
	proto.RegisterType((*OrgBankAccount)(nil), "protos.OrgBankAccount")
}

func init() { proto.RegisterFile("financingorder/common.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 462 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x84, 0x93, 0xdf, 0x8a, 0x13, 0x31,
	0x14, 0xc6, 0xe9, 0xb6, 0x9d, 0x6e, 0xcf, 0xac, 0x22, 0x51, 0x74, 0xd8, 0x45, 0x56, 0x0a, 0x8b,
	0xe2, 0xc5, 0x0c, 0x54, 0x5c, 0x2f, 0xbc, 0xda, 0x5e, 0x08, 0x45, 0xd9, 0x85, 0x41, 0xbd, 0xf0,
	0x66, 0xc8, 0xa4, 0xe9, 0x34, 0xec, 0x4c, 0x12, 0x92, 0x0c, 0x5d, 0x7d, 0x0a, 0x9f, 0xc8, 0x67,
	0x93, 0x9c, 0x64, 0xac, 0x0b, 0x82, 0x57, 0x3d, 0xdf, 0x97, 0x93, 0xe6, 0x77, 0xfe, 0x0c, 0x9c,
	0x6d, 0x85, 0xa4, 0x92, 0x09, 0xd9, 0x28, 0xb3, 0xe1, 0xa6, 0x60, 0xaa, 0xeb, 0x94, 0xcc, 0xb5,
	0x51, 0x4e, 0x91, 0x04, 0x7f, 0xec, 0xe9, 0x79, 0xa3, 0x54, 0xd3, 0xf2, 0x02, 0x65, 0xdd, 0x6f,
	0x0b, 0x27, 0x3a, 0x6e, 0x1d, 0xed, 0x74, 0x48, 0x5c, 0x7c, 0x84, 0xe9, 0x95, 0xd6, 0x5f, 0x15,
	0x79, 0x02, 0x53, 0xaa, 0xf5, 0x7a, 0x93, 0x8d, 0x5e, 0x8c, 0x5e, 0xcd, 0xcb, 0x20, 0x48, 0x06,
	0x33, 0xaa, 0xf5, 0x35, 0xed, 0x78, 0x76, 0x84, 0xfe, 0x20, 0x09, 0x81, 0x89, 0xfb, 0xae, 0x79,
	0x36, 0x46, 0x1b, 0xe3, 0xc5, 0xcf, 0x23, 0x48, 0x6f, 0x34, 0x37, 0xd4, 0xf1, 0xb5, 0xdc, 0x2a,
	0xf2, 0x12, 0x66, 0xcc, 0x70, 0xea, 0xb8, 0xc1, 0x7f, 0x4d, 0x97, 0x0f, 0xc2, 0xab, 0x36, 0xc7,
	0x37, 0xcb, 0xe1, 0x94, 0xbc, 0x87, 0x34, 0x84, 0x95, 0xe7, 0xc3, 0xa7, 0xd2, 0xe5, 0x69, 0x1e,
	0xe0, 0xf3, 0x01, 0x3e, 0xff, 0x3c, 0xc0, 0x97, 0x10, 0xd2, 0xbd, 0x41, 0x9e, 0x43, 0x54, 0xa6,
	0x12, 0x3a, 0xf2, 0xcc, 0xa3, 0xb3, 0xd6, 0xe4, 0x35, 0xcc, 0x5b, 0x6a, 0x5d, 0xd5, 0x5b, 0x6e,
	0xb2, 0xc9, 0xbf, 0x30, 0x8e, 0xfd, 0xf9, 0x17, 0xcb, 0x0d, 0x79, 0x17, 0x73, 0x91, 0x62, 0xfa,
	0x5f, 0x0a, 0xbc, 0x88, 0x0c, 0xcf, 0x60, 0x86, 0x17, 0x85, 0xce, 0x12, 0x04, 0x48, 0xbc, 0x5c,
	0xeb, 0xc5, 0xaf, 0x11, 0xc0, 0x27, 0xbe, 0x69, 0xb8, 0xf9, 0x20, 0x5a, 0x4e, 0x1e, 0xc1, 0xb8,
	0x37, 0x6d, 0xec, 0xb1, 0x0f, 0x7d, 0x1f, 0x37, 0xd4, 0x51, 0xac, 0xf9, 0xa4, 0xc4, 0x98, 0x3c,
	0x85, 0xc4, 0xee, 0xe8, 0xf2, 0xed, 0x65, 0xac, 0x26, 0x2a, 0x9f, 0x2b, 0xfd, 0x28, 0x26, 0xa1,
	0xe7, 0x32, 0xce, 0xc1, 0x8a, 0x1f, 0x81, 0x76, 0x5c, 0x62, 0xfc, 0x67, 0x36, 0xc9, 0x61, 0x36,
	0xe4, 0x12, 0x4e, 0x54, 0x18, 0x4d, 0x25, 0xe4, 0x56, 0x65, 0x33, 0xac, 0xee, 0xf1, 0xd0, 0x89,
	0xbf, 0xc6, 0x56, 0xa6, 0xea, 0x20, 0x16, 0x3b, 0x78, 0x78, 0x63, 0x9a, 0x15, 0x95, 0xb7, 0x57,
	0x8c, 0xa9, 0x5e, 0x3a, 0xdc, 0x89, 0x10, 0xc6, 0x3a, 0x06, 0x49, 0xce, 0x60, 0x5e, 0x53, 0x79,
	0x5b, 0xc9, 0xc3, 0xbe, 0x1c, 0x7b, 0x03, 0x17, 0xe6, 0x1c, 0x52, 0x3c, 0xac, 0x0d, 0x95, 0x6c,
	0x17, 0x2b, 0x03, 0x6f, 0xad, 0xd0, 0x59, 0x5d, 0xc3, 0x05, 0x53, 0x5d, 0x7e, 0x27, 0xa8, 0x6c,
	0x24, 0xcd, 0xf7, 0xfb, 0xfd, 0x00, 0x77, 0x7f, 0xd3, 0xbf, 0x5d, 0x34, 0xc2, 0xed, 0xfa, 0x3a,
	0x67, 0xaa, 0x2b, 0xee, 0x24, 0x63, 0x61, 0xbb, 0x6d, 0x71, 0x3f, 0xad, 0x0e, 0xdf, 0xc0, 0x9b,
	0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xf7, 0x91, 0x02, 0x31, 0x29, 0x03, 0x00, 0x00,
}
