// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/order/order.proto

package com.github.example.protos.order;

public final class Order {
  private Order() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface OrderExampleOrBuilder extends
      // @@protoc_insertion_point(interface_extends:order.OrderExample)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string no = 1;</code>
     */
    java.lang.String getNo();
    /**
     * <code>optional string no = 1;</code>
     */
    com.google.protobuf.ByteString
        getNoBytes();

    /**
     * <code>optional int32 days = 2;</code>
     */
    int getDays();

    /**
     * <code>optional int64 money = 3;</code>
     */
    long getMoney();

    /**
     * <code>optional int64 time = 4;</code>
     */
    long getTime();

    /**
     * <code>optional .google.protobuf.Timestamp timestamp = 5;</code>
     */
    boolean hasTimestamp();
    /**
     * <code>optional .google.protobuf.Timestamp timestamp = 5;</code>
     */
    com.google.protobuf.Timestamp getTimestamp();
    /**
     * <code>optional .google.protobuf.Timestamp timestamp = 5;</code>
     */
    com.google.protobuf.TimestampOrBuilder getTimestampOrBuilder();
  }
  /**
   * Protobuf type {@code order.OrderExample}
   */
  public  static final class OrderExample extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:order.OrderExample)
      OrderExampleOrBuilder {
    // Use OrderExample.newBuilder() to construct.
    private OrderExample(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private OrderExample() {
      no_ = "";
      days_ = 0;
      money_ = 0L;
      time_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private OrderExample(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              no_ = s;
              break;
            }
            case 16: {

              days_ = input.readInt32();
              break;
            }
            case 24: {

              money_ = input.readInt64();
              break;
            }
            case 32: {

              time_ = input.readInt64();
              break;
            }
            case 42: {
              com.google.protobuf.Timestamp.Builder subBuilder = null;
              if (timestamp_ != null) {
                subBuilder = timestamp_.toBuilder();
              }
              timestamp_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(timestamp_);
                timestamp_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.example.protos.order.Order.internal_static_order_OrderExample_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.example.protos.order.Order.internal_static_order_OrderExample_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.example.protos.order.Order.OrderExample.class, com.github.example.protos.order.Order.OrderExample.Builder.class);
    }

    public static final int NO_FIELD_NUMBER = 1;
    private volatile java.lang.Object no_;
    /**
     * <code>optional string no = 1;</code>
     */
    public java.lang.String getNo() {
      java.lang.Object ref = no_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        no_ = s;
        return s;
      }
    }
    /**
     * <code>optional string no = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNoBytes() {
      java.lang.Object ref = no_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        no_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DAYS_FIELD_NUMBER = 2;
    private int days_;
    /**
     * <code>optional int32 days = 2;</code>
     */
    public int getDays() {
      return days_;
    }

    public static final int MONEY_FIELD_NUMBER = 3;
    private long money_;
    /**
     * <code>optional int64 money = 3;</code>
     */
    public long getMoney() {
      return money_;
    }

    public static final int TIME_FIELD_NUMBER = 4;
    private long time_;
    /**
     * <code>optional int64 time = 4;</code>
     */
    public long getTime() {
      return time_;
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 5;
    private com.google.protobuf.Timestamp timestamp_;
    /**
     * <code>optional .google.protobuf.Timestamp timestamp = 5;</code>
     */
    public boolean hasTimestamp() {
      return timestamp_ != null;
    }
    /**
     * <code>optional .google.protobuf.Timestamp timestamp = 5;</code>
     */
    public com.google.protobuf.Timestamp getTimestamp() {
      return timestamp_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : timestamp_;
    }
    /**
     * <code>optional .google.protobuf.Timestamp timestamp = 5;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getTimestampOrBuilder() {
      return getTimestamp();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNoBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, no_);
      }
      if (days_ != 0) {
        output.writeInt32(2, days_);
      }
      if (money_ != 0L) {
        output.writeInt64(3, money_);
      }
      if (time_ != 0L) {
        output.writeInt64(4, time_);
      }
      if (timestamp_ != null) {
        output.writeMessage(5, getTimestamp());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNoBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, no_);
      }
      if (days_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, days_);
      }
      if (money_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, money_);
      }
      if (time_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, time_);
      }
      if (timestamp_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, getTimestamp());
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.github.example.protos.order.Order.OrderExample)) {
        return super.equals(obj);
      }
      com.github.example.protos.order.Order.OrderExample other = (com.github.example.protos.order.Order.OrderExample) obj;

      boolean result = true;
      result = result && getNo()
          .equals(other.getNo());
      result = result && (getDays()
          == other.getDays());
      result = result && (getMoney()
          == other.getMoney());
      result = result && (getTime()
          == other.getTime());
      result = result && (hasTimestamp() == other.hasTimestamp());
      if (hasTimestamp()) {
        result = result && getTimestamp()
            .equals(other.getTimestamp());
      }
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + NO_FIELD_NUMBER;
      hash = (53 * hash) + getNo().hashCode();
      hash = (37 * hash) + DAYS_FIELD_NUMBER;
      hash = (53 * hash) + getDays();
      hash = (37 * hash) + MONEY_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getMoney());
      hash = (37 * hash) + TIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTime());
      if (hasTimestamp()) {
        hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
        hash = (53 * hash) + getTimestamp().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.github.example.protos.order.Order.OrderExample parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.example.protos.order.Order.OrderExample parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.example.protos.order.Order.OrderExample parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.example.protos.order.Order.OrderExample parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.example.protos.order.Order.OrderExample parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.example.protos.order.Order.OrderExample parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.example.protos.order.Order.OrderExample parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.github.example.protos.order.Order.OrderExample parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.example.protos.order.Order.OrderExample parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.example.protos.order.Order.OrderExample parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.github.example.protos.order.Order.OrderExample prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code order.OrderExample}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:order.OrderExample)
        com.github.example.protos.order.Order.OrderExampleOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.github.example.protos.order.Order.internal_static_order_OrderExample_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.github.example.protos.order.Order.internal_static_order_OrderExample_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.github.example.protos.order.Order.OrderExample.class, com.github.example.protos.order.Order.OrderExample.Builder.class);
      }

      // Construct using com.github.example.protos.order.Order.OrderExample.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        no_ = "";

        days_ = 0;

        money_ = 0L;

        time_ = 0L;

        if (timestampBuilder_ == null) {
          timestamp_ = null;
        } else {
          timestamp_ = null;
          timestampBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.github.example.protos.order.Order.internal_static_order_OrderExample_descriptor;
      }

      public com.github.example.protos.order.Order.OrderExample getDefaultInstanceForType() {
        return com.github.example.protos.order.Order.OrderExample.getDefaultInstance();
      }

      public com.github.example.protos.order.Order.OrderExample build() {
        com.github.example.protos.order.Order.OrderExample result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.github.example.protos.order.Order.OrderExample buildPartial() {
        com.github.example.protos.order.Order.OrderExample result = new com.github.example.protos.order.Order.OrderExample(this);
        result.no_ = no_;
        result.days_ = days_;
        result.money_ = money_;
        result.time_ = time_;
        if (timestampBuilder_ == null) {
          result.timestamp_ = timestamp_;
        } else {
          result.timestamp_ = timestampBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.github.example.protos.order.Order.OrderExample) {
          return mergeFrom((com.github.example.protos.order.Order.OrderExample)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.github.example.protos.order.Order.OrderExample other) {
        if (other == com.github.example.protos.order.Order.OrderExample.getDefaultInstance()) return this;
        if (!other.getNo().isEmpty()) {
          no_ = other.no_;
          onChanged();
        }
        if (other.getDays() != 0) {
          setDays(other.getDays());
        }
        if (other.getMoney() != 0L) {
          setMoney(other.getMoney());
        }
        if (other.getTime() != 0L) {
          setTime(other.getTime());
        }
        if (other.hasTimestamp()) {
          mergeTimestamp(other.getTimestamp());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.github.example.protos.order.Order.OrderExample parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.github.example.protos.order.Order.OrderExample) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object no_ = "";
      /**
       * <code>optional string no = 1;</code>
       */
      public java.lang.String getNo() {
        java.lang.Object ref = no_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          no_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string no = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNoBytes() {
        java.lang.Object ref = no_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          no_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string no = 1;</code>
       */
      public Builder setNo(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        no_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string no = 1;</code>
       */
      public Builder clearNo() {
        
        no_ = getDefaultInstance().getNo();
        onChanged();
        return this;
      }
      /**
       * <code>optional string no = 1;</code>
       */
      public Builder setNoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        no_ = value;
        onChanged();
        return this;
      }

      private int days_ ;
      /**
       * <code>optional int32 days = 2;</code>
       */
      public int getDays() {
        return days_;
      }
      /**
       * <code>optional int32 days = 2;</code>
       */
      public Builder setDays(int value) {
        
        days_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 days = 2;</code>
       */
      public Builder clearDays() {
        
        days_ = 0;
        onChanged();
        return this;
      }

      private long money_ ;
      /**
       * <code>optional int64 money = 3;</code>
       */
      public long getMoney() {
        return money_;
      }
      /**
       * <code>optional int64 money = 3;</code>
       */
      public Builder setMoney(long value) {
        
        money_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 money = 3;</code>
       */
      public Builder clearMoney() {
        
        money_ = 0L;
        onChanged();
        return this;
      }

      private long time_ ;
      /**
       * <code>optional int64 time = 4;</code>
       */
      public long getTime() {
        return time_;
      }
      /**
       * <code>optional int64 time = 4;</code>
       */
      public Builder setTime(long value) {
        
        time_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 time = 4;</code>
       */
      public Builder clearTime() {
        
        time_ = 0L;
        onChanged();
        return this;
      }

      private com.google.protobuf.Timestamp timestamp_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> timestampBuilder_;
      /**
       * <code>optional .google.protobuf.Timestamp timestamp = 5;</code>
       */
      public boolean hasTimestamp() {
        return timestampBuilder_ != null || timestamp_ != null;
      }
      /**
       * <code>optional .google.protobuf.Timestamp timestamp = 5;</code>
       */
      public com.google.protobuf.Timestamp getTimestamp() {
        if (timestampBuilder_ == null) {
          return timestamp_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : timestamp_;
        } else {
          return timestampBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .google.protobuf.Timestamp timestamp = 5;</code>
       */
      public Builder setTimestamp(com.google.protobuf.Timestamp value) {
        if (timestampBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          timestamp_ = value;
          onChanged();
        } else {
          timestampBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .google.protobuf.Timestamp timestamp = 5;</code>
       */
      public Builder setTimestamp(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        if (timestampBuilder_ == null) {
          timestamp_ = builderForValue.build();
          onChanged();
        } else {
          timestampBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .google.protobuf.Timestamp timestamp = 5;</code>
       */
      public Builder mergeTimestamp(com.google.protobuf.Timestamp value) {
        if (timestampBuilder_ == null) {
          if (timestamp_ != null) {
            timestamp_ =
              com.google.protobuf.Timestamp.newBuilder(timestamp_).mergeFrom(value).buildPartial();
          } else {
            timestamp_ = value;
          }
          onChanged();
        } else {
          timestampBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .google.protobuf.Timestamp timestamp = 5;</code>
       */
      public Builder clearTimestamp() {
        if (timestampBuilder_ == null) {
          timestamp_ = null;
          onChanged();
        } else {
          timestamp_ = null;
          timestampBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .google.protobuf.Timestamp timestamp = 5;</code>
       */
      public com.google.protobuf.Timestamp.Builder getTimestampBuilder() {
        
        onChanged();
        return getTimestampFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .google.protobuf.Timestamp timestamp = 5;</code>
       */
      public com.google.protobuf.TimestampOrBuilder getTimestampOrBuilder() {
        if (timestampBuilder_ != null) {
          return timestampBuilder_.getMessageOrBuilder();
        } else {
          return timestamp_ == null ?
              com.google.protobuf.Timestamp.getDefaultInstance() : timestamp_;
        }
      }
      /**
       * <code>optional .google.protobuf.Timestamp timestamp = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
          getTimestampFieldBuilder() {
        if (timestampBuilder_ == null) {
          timestampBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                  getTimestamp(),
                  getParentForChildren(),
                  isClean());
          timestamp_ = null;
        }
        return timestampBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:order.OrderExample)
    }

    // @@protoc_insertion_point(class_scope:order.OrderExample)
    private static final com.github.example.protos.order.Order.OrderExample DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.github.example.protos.order.Order.OrderExample();
    }

    public static com.github.example.protos.order.Order.OrderExample getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<OrderExample>
        PARSER = new com.google.protobuf.AbstractParser<OrderExample>() {
      public OrderExample parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new OrderExample(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<OrderExample> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<OrderExample> getParserForType() {
      return PARSER;
    }

    public com.github.example.protos.order.Order.OrderExample getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_order_OrderExample_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_order_OrderExample_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030protos/order/order.proto\022\005order\032\037googl" +
      "e/protobuf/timestamp.proto\"t\n\014OrderExamp" +
      "le\022\n\n\002no\030\001 \001(\t\022\014\n\004days\030\002 \001(\005\022\r\n\005money\030\003 " +
      "\001(\003\022\014\n\004time\030\004 \001(\003\022-\n\ttimestamp\030\005 \001(\0132\032.g" +
      "oogle.protobuf.TimestampBE\n\037com.github.e" +
      "xample.protos.orderZ\"github.com/example_" +
      "cc/protos/orderb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        }, assigner);
    internal_static_order_OrderExample_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_order_OrderExample_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_order_OrderExample_descriptor,
        new java.lang.String[] { "No", "Days", "Money", "Time", "Timestamp", });
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
