// Code generated by protoc-gen-go.
// source: contract/contract.proto
// DO NOT EDIT!

/*
Package contract is a generated protocol buffer package.

It is generated from these files:
	contract/contract.proto
	contract/contract_request.proto

It has these top-level messages:
	FinancingContract
	ContractData
	FinancingInvoice
	Invoice
	ContractMoneyCount
	ContractTransactionDetail
	ContractStatus
	BankLoanContract
	FinancingContractReview
	ContractCheckFlowInfo
	ContractCheckFlowData
	ContractStepCheckData
	CheckData
	ContractExcuteRequest
	ContractAddCheckLogRequest
	ContractQueryRequest
*/
package contract

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/timestamp"
import protos "github.com/xncc/protos/common"
import protos1 "github.com/xncc/protos/configuration"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// ======================================三方账本融资申请订单数据=============================================
// 供应商到保理融资申请订单
type FinancingContract struct {
	OrderNo           string               `protobuf:"bytes,1,opt,name=order_no,json=orderNo" json:"order_no,omitempty"`
	Supplier          *protos.AppVo        `protobuf:"bytes,2,opt,name=supplier" json:"supplier,omitempty"`
	Enterprise        *protos.AppVo        `protobuf:"bytes,3,opt,name=enterprise" json:"enterprise,omitempty"`
	BankFactor        *protos.AppVo        `protobuf:"bytes,4,opt,name=bank_factor,json=bankFactor" json:"bank_factor,omitempty"`
	ContractData      *ContractData        `protobuf:"bytes,5,opt,name=contract_data,json=contractData" json:"contract_data,omitempty"`
	Invoices          []*FinancingInvoice  `protobuf:"bytes,6,rep,name=invoices" json:"invoices,omitempty"`
	OrderFilesEncrypt []*protos.LedgerFile `protobuf:"bytes,7,rep,name=order_files_encrypt,json=orderFilesEncrypt" json:"order_files_encrypt,omitempty"`
	MoneyCount        *ContractMoneyCount  `protobuf:"bytes,8,opt,name=money_count,json=moneyCount" json:"money_count,omitempty"`
	ContractStatus    *ContractStatus      `protobuf:"bytes,9,opt,name=contract_status,json=contractStatus" json:"contract_status,omitempty"`
	OperateInfo       *protos.OperateInfo  `protobuf:"bytes,10,opt,name=operate_info,json=operateInfo" json:"operate_info,omitempty"`
}

func (m *FinancingContract) Reset()                    { *m = FinancingContract{} }
func (m *FinancingContract) String() string            { return proto.CompactTextString(m) }
func (*FinancingContract) ProtoMessage()               {}
func (*FinancingContract) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *FinancingContract) GetOrderNo() string {
	if m != nil {
		return m.OrderNo
	}
	return ""
}

func (m *FinancingContract) GetSupplier() *protos.AppVo {
	if m != nil {
		return m.Supplier
	}
	return nil
}

func (m *FinancingContract) GetEnterprise() *protos.AppVo {
	if m != nil {
		return m.Enterprise
	}
	return nil
}

func (m *FinancingContract) GetBankFactor() *protos.AppVo {
	if m != nil {
		return m.BankFactor
	}
	return nil
}

func (m *FinancingContract) GetContractData() *ContractData {
	if m != nil {
		return m.ContractData
	}
	return nil
}

func (m *FinancingContract) GetInvoices() []*FinancingInvoice {
	if m != nil {
		return m.Invoices
	}
	return nil
}

func (m *FinancingContract) GetOrderFilesEncrypt() []*protos.LedgerFile {
	if m != nil {
		return m.OrderFilesEncrypt
	}
	return nil
}

func (m *FinancingContract) GetMoneyCount() *ContractMoneyCount {
	if m != nil {
		return m.MoneyCount
	}
	return nil
}

func (m *FinancingContract) GetContractStatus() *ContractStatus {
	if m != nil {
		return m.ContractStatus
	}
	return nil
}

func (m *FinancingContract) GetOperateInfo() *protos.OperateInfo {
	if m != nil {
		return m.OperateInfo
	}
	return nil
}

// 订单表单数据
type ContractData struct {
	// 发起申请方维护字段
	ExpectAmount      int64                      `protobuf:"varint,1,opt,name=expect_amount,json=expectAmount" json:"expect_amount,omitempty"`
	FinancingPeriod   int32                      `protobuf:"varint,2,opt,name=financing_period,json=financingPeriod" json:"financing_period,omitempty"`
	ExpectExpiredTime *google_protobuf.Timestamp `protobuf:"bytes,3,opt,name=expect_expired_time,json=expectExpiredTime" json:"expect_expired_time,omitempty"`
	// 最终放款方维护字段
	ConfirmedAmount      int64                      `protobuf:"varint,4,opt,name=confirmed_amount,json=confirmedAmount" json:"confirmed_amount,omitempty"`
	ConfirmedExpiredTime *google_protobuf.Timestamp `protobuf:"bytes,5,opt,name=confirmed_expired_time,json=confirmedExpiredTime" json:"confirmed_expired_time,omitempty"`
	ConfirmedRate        int64                      `protobuf:"varint,6,opt,name=confirmed_rate,json=confirmedRate" json:"confirmed_rate,omitempty"`
	OrderFiles           []*protos.LedgerFile       `protobuf:"bytes,7,rep,name=order_files,json=orderFiles" json:"order_files,omitempty"`
}

func (m *ContractData) Reset()                    { *m = ContractData{} }
func (m *ContractData) String() string            { return proto.CompactTextString(m) }
func (*ContractData) ProtoMessage()               {}
func (*ContractData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ContractData) GetExpectAmount() int64 {
	if m != nil {
		return m.ExpectAmount
	}
	return 0
}

func (m *ContractData) GetFinancingPeriod() int32 {
	if m != nil {
		return m.FinancingPeriod
	}
	return 0
}

func (m *ContractData) GetExpectExpiredTime() *google_protobuf.Timestamp {
	if m != nil {
		return m.ExpectExpiredTime
	}
	return nil
}

func (m *ContractData) GetConfirmedAmount() int64 {
	if m != nil {
		return m.ConfirmedAmount
	}
	return 0
}

func (m *ContractData) GetConfirmedExpiredTime() *google_protobuf.Timestamp {
	if m != nil {
		return m.ConfirmedExpiredTime
	}
	return nil
}

func (m *ContractData) GetConfirmedRate() int64 {
	if m != nil {
		return m.ConfirmedRate
	}
	return 0
}

func (m *ContractData) GetOrderFiles() []*protos.LedgerFile {
	if m != nil {
		return m.OrderFiles
	}
	return nil
}

// 一张发票的融资信息
type FinancingInvoice struct {
	Invoice               *Invoice                   `protobuf:"bytes,1,opt,name=invoice" json:"invoice,omitempty"`
	ExpectAmount          int64                      `protobuf:"varint,2,opt,name=expect_amount,json=expectAmount" json:"expect_amount,omitempty"`
	ConfirmAmount         int64                      `protobuf:"varint,3,opt,name=confirm_amount,json=confirmAmount" json:"confirm_amount,omitempty"`
	ConfirmRate           int64                      `protobuf:"varint,4,opt,name=confirm_rate,json=confirmRate" json:"confirm_rate,omitempty"`
	ConfirmPayTime        *google_protobuf.Timestamp `protobuf:"bytes,5,opt,name=confirm_pay_time,json=confirmPayTime" json:"confirm_pay_time,omitempty"`
	ConfirmReturnTime     *google_protobuf.Timestamp `protobuf:"bytes,6,opt,name=confirm_return_time,json=confirmReturnTime" json:"confirm_return_time,omitempty"`
	ConfirmEndTime        *google_protobuf.Timestamp `protobuf:"bytes,7,opt,name=confirm_end_time,json=confirmEndTime" json:"confirm_end_time,omitempty"`
	ConfirmRateDesc       string                     `protobuf:"bytes,8,opt,name=confirm_rate_desc,json=confirmRateDesc" json:"confirm_rate_desc,omitempty"`
	ConfirmUrgeReturnDesc string                     `protobuf:"bytes,9,opt,name=confirm_urge_return_desc,json=confirmUrgeReturnDesc" json:"confirm_urge_return_desc,omitempty"`
}

func (m *FinancingInvoice) Reset()                    { *m = FinancingInvoice{} }
func (m *FinancingInvoice) String() string            { return proto.CompactTextString(m) }
func (*FinancingInvoice) ProtoMessage()               {}
func (*FinancingInvoice) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *FinancingInvoice) GetInvoice() *Invoice {
	if m != nil {
		return m.Invoice
	}
	return nil
}

func (m *FinancingInvoice) GetExpectAmount() int64 {
	if m != nil {
		return m.ExpectAmount
	}
	return 0
}

func (m *FinancingInvoice) GetConfirmAmount() int64 {
	if m != nil {
		return m.ConfirmAmount
	}
	return 0
}

func (m *FinancingInvoice) GetConfirmRate() int64 {
	if m != nil {
		return m.ConfirmRate
	}
	return 0
}

func (m *FinancingInvoice) GetConfirmPayTime() *google_protobuf.Timestamp {
	if m != nil {
		return m.ConfirmPayTime
	}
	return nil
}

func (m *FinancingInvoice) GetConfirmReturnTime() *google_protobuf.Timestamp {
	if m != nil {
		return m.ConfirmReturnTime
	}
	return nil
}

func (m *FinancingInvoice) GetConfirmEndTime() *google_protobuf.Timestamp {
	if m != nil {
		return m.ConfirmEndTime
	}
	return nil
}

func (m *FinancingInvoice) GetConfirmRateDesc() string {
	if m != nil {
		return m.ConfirmRateDesc
	}
	return ""
}

func (m *FinancingInvoice) GetConfirmUrgeReturnDesc() string {
	if m != nil {
		return m.ConfirmUrgeReturnDesc
	}
	return ""
}

// 供应商发票信息
type Invoice struct {
	InvoiceNo     string                     `protobuf:"bytes,1,opt,name=invoice_no,json=invoiceNo" json:"invoice_no,omitempty"`
	InvoiceAmount int64                      `protobuf:"varint,2,opt,name=invoice_amount,json=invoiceAmount" json:"invoice_amount,omitempty"`
	InvoiceTime   *google_protobuf.Timestamp `protobuf:"bytes,3,opt,name=invoice_time,json=invoiceTime" json:"invoice_time,omitempty"`
	Supplier      *protos.AppVo              `protobuf:"bytes,4,opt,name=supplier" json:"supplier,omitempty"`
	Enterprise    *protos.AppVo              `protobuf:"bytes,5,opt,name=enterprise" json:"enterprise,omitempty"`
	Remark        string                     `protobuf:"bytes,6,opt,name=remark" json:"remark,omitempty"`
	Notes         []*protos.LedgerFile       `protobuf:"bytes,7,rep,name=notes" json:"notes,omitempty"`
	OperateInfo   *protos.OperateInfo        `protobuf:"bytes,8,opt,name=operate_info,json=operateInfo" json:"operate_info,omitempty"`
}

func (m *Invoice) Reset()                    { *m = Invoice{} }
func (m *Invoice) String() string            { return proto.CompactTextString(m) }
func (*Invoice) ProtoMessage()               {}
func (*Invoice) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Invoice) GetInvoiceNo() string {
	if m != nil {
		return m.InvoiceNo
	}
	return ""
}

func (m *Invoice) GetInvoiceAmount() int64 {
	if m != nil {
		return m.InvoiceAmount
	}
	return 0
}

func (m *Invoice) GetInvoiceTime() *google_protobuf.Timestamp {
	if m != nil {
		return m.InvoiceTime
	}
	return nil
}

func (m *Invoice) GetSupplier() *protos.AppVo {
	if m != nil {
		return m.Supplier
	}
	return nil
}

func (m *Invoice) GetEnterprise() *protos.AppVo {
	if m != nil {
		return m.Enterprise
	}
	return nil
}

func (m *Invoice) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

func (m *Invoice) GetNotes() []*protos.LedgerFile {
	if m != nil {
		return m.Notes
	}
	return nil
}

func (m *Invoice) GetOperateInfo() *protos.OperateInfo {
	if m != nil {
		return m.OperateInfo
	}
	return nil
}

// 订单款项金额汇总
type ContractMoneyCount struct {
	// 下面为结算字段,具体流水记录到交易明细,此处体现订单总金额
	// 放款
	NeedPayAmount  int64 `protobuf:"varint,1,opt,name=need_pay_amount,json=needPayAmount" json:"need_pay_amount,omitempty"`
	ExpensesAmount int64 `protobuf:"varint,2,opt,name=expenses_amount,json=expensesAmount" json:"expenses_amount,omitempty"`
	IncomeAmount   int64 `protobuf:"varint,3,opt,name=income_amount,json=incomeAmount" json:"income_amount,omitempty"`
	// 还款
	NeedPaybackLoanAmount int64 `protobuf:"varint,4,opt,name=need_payback_loan_amount,json=needPaybackLoanAmount" json:"need_payback_loan_amount,omitempty"`
	PaybackExpensesAmount int64 `protobuf:"varint,5,opt,name=payback_expenses_amount,json=paybackExpensesAmount" json:"payback_expenses_amount,omitempty"`
	PaybackIncomeAmount   int64 `protobuf:"varint,6,opt,name=payback_income_amount,json=paybackIncomeAmount" json:"payback_income_amount,omitempty"`
	// 所有在申请订单内发生的金额交易(转账)都应该在此处有明确的流水
	TransactionDetails []*ContractTransactionDetail `protobuf:"bytes,7,rep,name=transaction_details,json=transactionDetails" json:"transaction_details,omitempty"`
}

func (m *ContractMoneyCount) Reset()                    { *m = ContractMoneyCount{} }
func (m *ContractMoneyCount) String() string            { return proto.CompactTextString(m) }
func (*ContractMoneyCount) ProtoMessage()               {}
func (*ContractMoneyCount) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *ContractMoneyCount) GetNeedPayAmount() int64 {
	if m != nil {
		return m.NeedPayAmount
	}
	return 0
}

func (m *ContractMoneyCount) GetExpensesAmount() int64 {
	if m != nil {
		return m.ExpensesAmount
	}
	return 0
}

func (m *ContractMoneyCount) GetIncomeAmount() int64 {
	if m != nil {
		return m.IncomeAmount
	}
	return 0
}

func (m *ContractMoneyCount) GetNeedPaybackLoanAmount() int64 {
	if m != nil {
		return m.NeedPaybackLoanAmount
	}
	return 0
}

func (m *ContractMoneyCount) GetPaybackExpensesAmount() int64 {
	if m != nil {
		return m.PaybackExpensesAmount
	}
	return 0
}

func (m *ContractMoneyCount) GetPaybackIncomeAmount() int64 {
	if m != nil {
		return m.PaybackIncomeAmount
	}
	return 0
}

func (m *ContractMoneyCount) GetTransactionDetails() []*ContractTransactionDetail {
	if m != nil {
		return m.TransactionDetails
	}
	return nil
}

// 订单款项转移金额流水
type ContractTransactionDetail struct {
	Expenses         *protos.AppVo              `protobuf:"bytes,1,opt,name=expenses" json:"expenses,omitempty"`
	ExpensesAmount   int64                      `protobuf:"varint,2,opt,name=expenses_amount,json=expensesAmount" json:"expenses_amount,omitempty"`
	ExpensesAccount  *protos.OrgBankAccount     `protobuf:"bytes,3,opt,name=expenses_account,json=expensesAccount" json:"expenses_account,omitempty"`
	Income           *protos.AppVo              `protobuf:"bytes,4,opt,name=income" json:"income,omitempty"`
	IncomeAccount    *protos.OrgBankAccount     `protobuf:"bytes,6,opt,name=income_account,json=incomeAccount" json:"income_account,omitempty"`
	TansactionRemark string                     `protobuf:"bytes,7,opt,name=tansaction_remark,json=tansactionRemark" json:"tansaction_remark,omitempty"`
	TansactionNotes  []*protos.LedgerFile       `protobuf:"bytes,8,rep,name=tansaction_notes,json=tansactionNotes" json:"tansaction_notes,omitempty"`
	TansactionTime   *google_protobuf.Timestamp `protobuf:"bytes,9,opt,name=tansaction_time,json=tansactionTime" json:"tansaction_time,omitempty"`
	IncomConfirm     bool                       `protobuf:"varint,10,opt,name=incom_confirm,json=incomConfirm" json:"incom_confirm,omitempty"`
	OperateInfo      *protos.OperateInfo        `protobuf:"bytes,11,opt,name=operate_info,json=operateInfo" json:"operate_info,omitempty"`
}

func (m *ContractTransactionDetail) Reset()                    { *m = ContractTransactionDetail{} }
func (m *ContractTransactionDetail) String() string            { return proto.CompactTextString(m) }
func (*ContractTransactionDetail) ProtoMessage()               {}
func (*ContractTransactionDetail) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *ContractTransactionDetail) GetExpenses() *protos.AppVo {
	if m != nil {
		return m.Expenses
	}
	return nil
}

func (m *ContractTransactionDetail) GetExpensesAmount() int64 {
	if m != nil {
		return m.ExpensesAmount
	}
	return 0
}

func (m *ContractTransactionDetail) GetExpensesAccount() *protos.OrgBankAccount {
	if m != nil {
		return m.ExpensesAccount
	}
	return nil
}

func (m *ContractTransactionDetail) GetIncome() *protos.AppVo {
	if m != nil {
		return m.Income
	}
	return nil
}

func (m *ContractTransactionDetail) GetIncomeAccount() *protos.OrgBankAccount {
	if m != nil {
		return m.IncomeAccount
	}
	return nil
}

func (m *ContractTransactionDetail) GetTansactionRemark() string {
	if m != nil {
		return m.TansactionRemark
	}
	return ""
}

func (m *ContractTransactionDetail) GetTansactionNotes() []*protos.LedgerFile {
	if m != nil {
		return m.TansactionNotes
	}
	return nil
}

func (m *ContractTransactionDetail) GetTansactionTime() *google_protobuf.Timestamp {
	if m != nil {
		return m.TansactionTime
	}
	return nil
}

func (m *ContractTransactionDetail) GetIncomConfirm() bool {
	if m != nil {
		return m.IncomConfirm
	}
	return false
}

func (m *ContractTransactionDetail) GetOperateInfo() *protos.OperateInfo {
	if m != nil {
		return m.OperateInfo
	}
	return nil
}

// 订单状态
type ContractStatus struct {
	CurrentStep    *protos1.ContractStep    `protobuf:"bytes,1,opt,name=current_step,json=currentStep" json:"current_step,omitempty"`
	CheckDatas     []*ContractStepCheckData `protobuf:"bytes,2,rep,name=check_datas,json=checkDatas" json:"check_datas,omitempty"`
	CheckFlowInfos []*ContractCheckFlowInfo `protobuf:"bytes,3,rep,name=check_flow_infos,json=checkFlowInfos" json:"check_flow_infos,omitempty"`
	StepHistory    []*protos1.ContractStep  `protobuf:"bytes,5,rep,name=step_history,json=stepHistory" json:"step_history,omitempty"`
}

func (m *ContractStatus) Reset()                    { *m = ContractStatus{} }
func (m *ContractStatus) String() string            { return proto.CompactTextString(m) }
func (*ContractStatus) ProtoMessage()               {}
func (*ContractStatus) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *ContractStatus) GetCurrentStep() *protos1.ContractStep {
	if m != nil {
		return m.CurrentStep
	}
	return nil
}

func (m *ContractStatus) GetCheckDatas() []*ContractStepCheckData {
	if m != nil {
		return m.CheckDatas
	}
	return nil
}

func (m *ContractStatus) GetCheckFlowInfos() []*ContractCheckFlowInfo {
	if m != nil {
		return m.CheckFlowInfos
	}
	return nil
}

func (m *ContractStatus) GetStepHistory() []*protos1.ContractStep {
	if m != nil {
		return m.StepHistory
	}
	return nil
}

// ========================================银行保理双方账本数据定义===========================================
// 融资申请订单
// 保理到银行贷款融资申请订单
type BankLoanContract struct {
	OrderNo                  string                     `protobuf:"bytes,1,opt,name=order_no,json=orderNo" json:"order_no,omitempty"`
	BankFactor               *protos.AppVo              `protobuf:"bytes,2,opt,name=bank_factor,json=bankFactor" json:"bank_factor,omitempty"`
	BankInfo                 *protos.AppVo              `protobuf:"bytes,3,opt,name=bank_info,json=bankInfo" json:"bank_info,omitempty"`
	ContractData             *ContractData              `protobuf:"bytes,4,opt,name=contract_data,json=contractData" json:"contract_data,omitempty"`
	FinancingContractReviews []*FinancingContractReview `protobuf:"bytes,5,rep,name=financing_contract_reviews,json=financingContractReviews" json:"financing_contract_reviews,omitempty"`
	MoneyCount               *ContractMoneyCount        `protobuf:"bytes,6,opt,name=money_count,json=moneyCount" json:"money_count,omitempty"`
	ContractStatus           *ContractStatus            `protobuf:"bytes,7,opt,name=contract_status,json=contractStatus" json:"contract_status,omitempty"`
	OperateInfo              *protos.OperateInfo        `protobuf:"bytes,8,opt,name=operate_info,json=operateInfo" json:"operate_info,omitempty"`
}

func (m *BankLoanContract) Reset()                    { *m = BankLoanContract{} }
func (m *BankLoanContract) String() string            { return proto.CompactTextString(m) }
func (*BankLoanContract) ProtoMessage()               {}
func (*BankLoanContract) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *BankLoanContract) GetOrderNo() string {
	if m != nil {
		return m.OrderNo
	}
	return ""
}

func (m *BankLoanContract) GetBankFactor() *protos.AppVo {
	if m != nil {
		return m.BankFactor
	}
	return nil
}

func (m *BankLoanContract) GetBankInfo() *protos.AppVo {
	if m != nil {
		return m.BankInfo
	}
	return nil
}

func (m *BankLoanContract) GetContractData() *ContractData {
	if m != nil {
		return m.ContractData
	}
	return nil
}

func (m *BankLoanContract) GetFinancingContractReviews() []*FinancingContractReview {
	if m != nil {
		return m.FinancingContractReviews
	}
	return nil
}

func (m *BankLoanContract) GetMoneyCount() *ContractMoneyCount {
	if m != nil {
		return m.MoneyCount
	}
	return nil
}

func (m *BankLoanContract) GetContractStatus() *ContractStatus {
	if m != nil {
		return m.ContractStatus
	}
	return nil
}

func (m *BankLoanContract) GetOperateInfo() *protos.OperateInfo {
	if m != nil {
		return m.OperateInfo
	}
	return nil
}

// 保理到银行贷款融资申请订单质押的供应商融资申请订单
type FinancingContractReview struct {
	OrderNo          string                     `protobuf:"bytes,1,opt,name=order_no,json=orderNo" json:"order_no,omitempty"`
	OrderAmount      int64                      `protobuf:"varint,2,opt,name=order_amount,json=orderAmount" json:"order_amount,omitempty"`
	FinancingPeriod  int32                      `protobuf:"varint,3,opt,name=financing_period,json=financingPeriod" json:"financing_period,omitempty"`
	OrderExpiredTime *google_protobuf.Timestamp `protobuf:"bytes,4,opt,name=order_expired_time,json=orderExpiredTime" json:"order_expired_time,omitempty"`
	// 保理申请的融资金额
	ExpectAmount int64 `protobuf:"varint,5,opt,name=expect_amount,json=expectAmount" json:"expect_amount,omitempty"`
	ExpectRate   int64 `protobuf:"varint,6,opt,name=expect_rate,json=expectRate" json:"expect_rate,omitempty"`
	// 银行审批确认的融资金额
	ConfirmAmount      int64                      `protobuf:"varint,7,opt,name=confirm_amount,json=confirmAmount" json:"confirm_amount,omitempty"`
	ConfirmRate        int64                      `protobuf:"varint,8,opt,name=confirm_rate,json=confirmRate" json:"confirm_rate,omitempty"`
	Supplier           *protos.AppVo              `protobuf:"bytes,9,opt,name=supplier" json:"supplier,omitempty"`
	Enterprise         *protos.AppVo              `protobuf:"bytes,10,opt,name=enterprise" json:"enterprise,omitempty"`
	BankFactor         *protos.AppVo              `protobuf:"bytes,11,opt,name=bank_factor,json=bankFactor" json:"bank_factor,omitempty"`
	ConfirmExpiredTime *google_protobuf.Timestamp `protobuf:"bytes,12,opt,name=confirm_expired_time,json=confirmExpiredTime" json:"confirm_expired_time,omitempty"`
}

func (m *FinancingContractReview) Reset()                    { *m = FinancingContractReview{} }
func (m *FinancingContractReview) String() string            { return proto.CompactTextString(m) }
func (*FinancingContractReview) ProtoMessage()               {}
func (*FinancingContractReview) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *FinancingContractReview) GetOrderNo() string {
	if m != nil {
		return m.OrderNo
	}
	return ""
}

func (m *FinancingContractReview) GetOrderAmount() int64 {
	if m != nil {
		return m.OrderAmount
	}
	return 0
}

func (m *FinancingContractReview) GetFinancingPeriod() int32 {
	if m != nil {
		return m.FinancingPeriod
	}
	return 0
}

func (m *FinancingContractReview) GetOrderExpiredTime() *google_protobuf.Timestamp {
	if m != nil {
		return m.OrderExpiredTime
	}
	return nil
}

func (m *FinancingContractReview) GetExpectAmount() int64 {
	if m != nil {
		return m.ExpectAmount
	}
	return 0
}

func (m *FinancingContractReview) GetExpectRate() int64 {
	if m != nil {
		return m.ExpectRate
	}
	return 0
}

func (m *FinancingContractReview) GetConfirmAmount() int64 {
	if m != nil {
		return m.ConfirmAmount
	}
	return 0
}

func (m *FinancingContractReview) GetConfirmRate() int64 {
	if m != nil {
		return m.ConfirmRate
	}
	return 0
}

func (m *FinancingContractReview) GetSupplier() *protos.AppVo {
	if m != nil {
		return m.Supplier
	}
	return nil
}

func (m *FinancingContractReview) GetEnterprise() *protos.AppVo {
	if m != nil {
		return m.Enterprise
	}
	return nil
}

func (m *FinancingContractReview) GetBankFactor() *protos.AppVo {
	if m != nil {
		return m.BankFactor
	}
	return nil
}

func (m *FinancingContractReview) GetConfirmExpiredTime() *google_protobuf.Timestamp {
	if m != nil {
		return m.ConfirmExpiredTime
	}
	return nil
}

// ==============================订单流程记录=====================================================
// 订单审核流程信息
type ContractCheckFlowInfo struct {
	ContractStep   *protos1.ContractStep  `protobuf:"bytes,1,opt,name=contract_step,json=contractStep" json:"contract_step,omitempty"`
	CheckFlowDatas *ContractCheckFlowData `protobuf:"bytes,2,opt,name=check_flow_datas,json=checkFlowDatas" json:"check_flow_datas,omitempty"`
}

func (m *ContractCheckFlowInfo) Reset()                    { *m = ContractCheckFlowInfo{} }
func (m *ContractCheckFlowInfo) String() string            { return proto.CompactTextString(m) }
func (*ContractCheckFlowInfo) ProtoMessage()               {}
func (*ContractCheckFlowInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *ContractCheckFlowInfo) GetContractStep() *protos1.ContractStep {
	if m != nil {
		return m.ContractStep
	}
	return nil
}

func (m *ContractCheckFlowInfo) GetCheckFlowDatas() *ContractCheckFlowData {
	if m != nil {
		return m.CheckFlowDatas
	}
	return nil
}

// 订单审核流程数据
type ContractCheckFlowData struct {
	CheckApp        *protos.AppVo              `protobuf:"bytes,1,opt,name=check_app,json=checkApp" json:"check_app,omitempty"`
	CheckUserName   string                     `protobuf:"bytes,2,opt,name=check_user_name,json=checkUserName" json:"check_user_name,omitempty"`
	CheckUserMobile string                     `protobuf:"bytes,3,opt,name=check_user_mobile,json=checkUserMobile" json:"check_user_mobile,omitempty"`
	CheckTime       *google_protobuf.Timestamp `protobuf:"bytes,4,opt,name=check_time,json=checkTime" json:"check_time,omitempty"`
	CheckIp         string                     `protobuf:"bytes,5,opt,name=check_ip,json=checkIp" json:"check_ip,omitempty"`
	Status          string                     `protobuf:"bytes,6,opt,name=status" json:"status,omitempty"`
	Remark          string                     `protobuf:"bytes,7,opt,name=remark" json:"remark,omitempty"`
}

func (m *ContractCheckFlowData) Reset()                    { *m = ContractCheckFlowData{} }
func (m *ContractCheckFlowData) String() string            { return proto.CompactTextString(m) }
func (*ContractCheckFlowData) ProtoMessage()               {}
func (*ContractCheckFlowData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *ContractCheckFlowData) GetCheckApp() *protos.AppVo {
	if m != nil {
		return m.CheckApp
	}
	return nil
}

func (m *ContractCheckFlowData) GetCheckUserName() string {
	if m != nil {
		return m.CheckUserName
	}
	return ""
}

func (m *ContractCheckFlowData) GetCheckUserMobile() string {
	if m != nil {
		return m.CheckUserMobile
	}
	return ""
}

func (m *ContractCheckFlowData) GetCheckTime() *google_protobuf.Timestamp {
	if m != nil {
		return m.CheckTime
	}
	return nil
}

func (m *ContractCheckFlowData) GetCheckIp() string {
	if m != nil {
		return m.CheckIp
	}
	return ""
}

func (m *ContractCheckFlowData) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *ContractCheckFlowData) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

// 具体阶段的检查确认项
type ContractStepCheckData struct {
	CurrentStep *protos1.ContractStep `protobuf:"bytes,1,opt,name=current_step,json=currentStep" json:"current_step,omitempty"`
	CheckDatas  []*CheckData          `protobuf:"bytes,2,rep,name=check_datas,json=checkDatas" json:"check_datas,omitempty"`
}

func (m *ContractStepCheckData) Reset()                    { *m = ContractStepCheckData{} }
func (m *ContractStepCheckData) String() string            { return proto.CompactTextString(m) }
func (*ContractStepCheckData) ProtoMessage()               {}
func (*ContractStepCheckData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *ContractStepCheckData) GetCurrentStep() *protos1.ContractStep {
	if m != nil {
		return m.CurrentStep
	}
	return nil
}

func (m *ContractStepCheckData) GetCheckDatas() []*CheckData {
	if m != nil {
		return m.CheckDatas
	}
	return nil
}

// 检查项的内容
type CheckData struct {
	Org   *protos.AppVo `protobuf:"bytes,1,opt,name=org" json:"org,omitempty"`
	Title string        `protobuf:"bytes,2,opt,name=title" json:"title,omitempty"`
	Value string        `protobuf:"bytes,3,opt,name=value" json:"value,omitempty"`
}

func (m *CheckData) Reset()                    { *m = CheckData{} }
func (m *CheckData) String() string            { return proto.CompactTextString(m) }
func (*CheckData) ProtoMessage()               {}
func (*CheckData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *CheckData) GetOrg() *protos.AppVo {
	if m != nil {
		return m.Org
	}
	return nil
}

func (m *CheckData) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *CheckData) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func init() {
	proto.RegisterType((*FinancingContract)(nil), "protos.FinancingContract")
	proto.RegisterType((*ContractData)(nil), "protos.ContractData")
	proto.RegisterType((*FinancingInvoice)(nil), "protos.FinancingInvoice")
	proto.RegisterType((*Invoice)(nil), "protos.Invoice")
	proto.RegisterType((*ContractMoneyCount)(nil), "protos.ContractMoneyCount")
	proto.RegisterType((*ContractTransactionDetail)(nil), "protos.ContractTransactionDetail")
	proto.RegisterType((*ContractStatus)(nil), "protos.ContractStatus")
	proto.RegisterType((*BankLoanContract)(nil), "protos.BankLoanContract")
	proto.RegisterType((*FinancingContractReview)(nil), "protos.FinancingContractReview")
	proto.RegisterType((*ContractCheckFlowInfo)(nil), "protos.ContractCheckFlowInfo")
	proto.RegisterType((*ContractCheckFlowData)(nil), "protos.ContractCheckFlowData")
	proto.RegisterType((*ContractStepCheckData)(nil), "protos.ContractStepCheckData")
	proto.RegisterType((*CheckData)(nil), "protos.CheckData")
}

func init() { proto.RegisterFile("contract/contract.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1541 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xa4, 0x58, 0x5b, 0x6f, 0x13, 0x49,
	0x16, 0x56, 0xe2, 0xfb, 0xb1, 0x9d, 0x4b, 0x25, 0x40, 0x13, 0x09, 0x25, 0x18, 0xb1, 0x1b, 0x58,
	0xad, 0x23, 0x85, 0x15, 0x08, 0xad, 0xd8, 0x55, 0xae, 0x4b, 0x10, 0x84, 0xa8, 0x17, 0x56, 0xab,
	0x95, 0x56, 0xad, 0x4a, 0xb9, 0x6c, 0x5a, 0xb1, 0xab, 0x5a, 0xdd, 0x6d, 0x92, 0x3c, 0xcf, 0xbc,
	0xcd, 0x4f, 0x18, 0xcd, 0xd3, 0x48, 0xf3, 0x0b, 0xe6, 0xcf, 0xcc, 0xeb, 0xbc, 0xcd, 0xbf, 0x18,
	0xd5, 0xa9, 0xaa, 0xbe, 0xd8, 0x9d, 0xd8, 0x0c, 0x4f, 0xb8, 0xce, 0xf9, 0xce, 0xa9, 0x3a, 0xd7,
	0xfe, 0x08, 0xdc, 0x63, 0x52, 0xc4, 0x21, 0x65, 0xf1, 0x8e, 0xfd, 0xd1, 0x0d, 0x42, 0x19, 0x4b,
	0x52, 0xc5, 0x7f, 0xa2, 0x8d, 0xcd, 0x81, 0x94, 0x83, 0x21, 0xdf, 0xc1, 0xe3, 0xf9, 0xb8, 0xbf,
	0x13, 0xfb, 0x23, 0x1e, 0xc5, 0x74, 0x14, 0x68, 0xe0, 0xc6, 0x1a, 0x93, 0xa3, 0x91, 0x14, 0x3b,
	0xfa, 0x1f, 0x23, 0xdc, 0x62, 0x52, 0xf4, 0xfd, 0xc1, 0x38, 0xa4, 0xb1, 0x8f, 0x3a, 0xed, 0xbb,
	0x3f, 0x94, 0x97, 0x1a, 0xd1, 0xf9, 0xb1, 0x0c, 0xab, 0xc7, 0xbe, 0xa0, 0x82, 0xf9, 0x62, 0x70,
	0x60, 0xf4, 0xe4, 0x3e, 0xd4, 0x65, 0xd8, 0xe3, 0xa1, 0x27, 0xa4, 0xb3, 0xb0, 0xb5, 0xb0, 0xdd,
	0x70, 0x6b, 0x78, 0x3e, 0x95, 0xe4, 0x09, 0xd4, 0xa3, 0x71, 0x10, 0x0c, 0x7d, 0x1e, 0x3a, 0x8b,
	0x5b, 0x0b, 0xdb, 0xcd, 0xdd, 0xb6, 0x76, 0x15, 0x75, 0xf7, 0x82, 0xe0, 0x3f, 0xd2, 0x4d, 0xd4,
	0xe4, 0xaf, 0x00, 0x5c, 0xc4, 0x3c, 0x0c, 0x42, 0x3f, 0xe2, 0x4e, 0xa9, 0x08, 0x9c, 0x01, 0x90,
	0x2e, 0x34, 0xcf, 0xa9, 0xb8, 0xf0, 0xfa, 0x94, 0xc5, 0x32, 0x74, 0xca, 0x85, 0x78, 0x85, 0x38,
	0x46, 0x00, 0x79, 0x09, 0x6d, 0x1b, 0x90, 0xd7, 0xa3, 0x31, 0x75, 0x2a, 0x68, 0xb1, 0x6e, 0x2d,
	0x6c, 0x34, 0x87, 0x34, 0xa6, 0x6e, 0x8b, 0x65, 0x4e, 0xe4, 0x6f, 0x50, 0xf7, 0xc5, 0x67, 0xe9,
	0x33, 0x1e, 0x39, 0xd5, 0xad, 0xd2, 0x76, 0x73, 0xd7, 0xb1, 0x56, 0x49, 0x32, 0x4e, 0x34, 0xc0,
	0x4d, 0x90, 0x64, 0x1f, 0xd6, 0x74, 0x56, 0xfa, 0xfe, 0x90, 0x47, 0x1e, 0x17, 0x2c, 0xbc, 0x0e,
	0x62, 0xa7, 0x86, 0x0e, 0x88, 0x75, 0xf0, 0x96, 0xf7, 0x06, 0x3c, 0x3c, 0xf6, 0x87, 0xdc, 0x5d,
	0x45, 0xb8, 0xfa, 0x19, 0x1d, 0x69, 0x30, 0xf9, 0x3b, 0x34, 0x47, 0x52, 0xf0, 0x6b, 0x8f, 0xc9,
	0xb1, 0x88, 0x9d, 0x3a, 0x3e, 0x79, 0x63, 0xf2, 0xc9, 0xef, 0x14, 0xe4, 0x40, 0x21, 0x5c, 0x18,
	0x25, 0xbf, 0xc9, 0x3f, 0x61, 0x39, 0x89, 0x38, 0x8a, 0x69, 0x3c, 0x8e, 0x9c, 0x06, 0x3a, 0xb8,
	0x3b, 0xe9, 0xe0, 0xdf, 0xa8, 0x75, 0x97, 0x58, 0xee, 0x4c, 0x9e, 0x43, 0x4b, 0x06, 0x3c, 0xa4,
	0x31, 0xf7, 0x7c, 0xd1, 0x97, 0x0e, 0xa0, 0xf5, 0x9a, 0xb5, 0x7e, 0xaf, 0x75, 0x27, 0xa2, 0x2f,
	0xdd, 0xa6, 0x4c, 0x0f, 0x9d, 0x6f, 0x4a, 0xd0, 0xca, 0xa6, 0x93, 0x3c, 0x82, 0x36, 0xbf, 0x0a,
	0x38, 0x8b, 0x3d, 0x3a, 0xc2, 0x40, 0x54, 0x97, 0x94, 0xdc, 0x96, 0x16, 0xee, 0xa1, 0x8c, 0x3c,
	0x81, 0x95, 0xbe, 0xcd, 0xa6, 0x17, 0xf0, 0xd0, 0x97, 0x3d, 0x6c, 0x99, 0x8a, 0xbb, 0x9c, 0xc8,
	0xcf, 0x50, 0x4c, 0xde, 0xc0, 0x9a, 0xf1, 0xc7, 0xaf, 0x02, 0x3f, 0xe4, 0x3d, 0x4f, 0xf5, 0xb7,
	0xe9, 0x99, 0x8d, 0xae, 0x6e, 0xfe, 0xae, 0x6d, 0xfe, 0xee, 0x07, 0xdb, 0xfc, 0xee, 0xaa, 0x36,
	0x3b, 0xd2, 0x56, 0x4a, 0xae, 0xae, 0xc5, 0xb6, 0x0f, 0x47, 0xbc, 0x67, 0x9f, 0x57, 0xc6, 0xe7,
	0x2d, 0x27, 0x72, 0xf3, 0xc2, 0x33, 0xb8, 0x9b, 0x42, 0x73, 0x37, 0x57, 0x66, 0xde, 0xbc, 0x9e,
	0x58, 0x66, 0x2f, 0x7f, 0x0c, 0x4b, 0xa9, 0x47, 0x95, 0x3f, 0xa7, 0x8a, 0x57, 0xb7, 0x13, 0xa9,
	0x4b, 0x63, 0x4e, 0x9e, 0x41, 0x33, 0xd3, 0x4a, 0xb7, 0xb4, 0x10, 0xa4, 0x2d, 0xd4, 0xf9, 0xad,
	0x04, 0x2b, 0x93, 0xed, 0x49, 0x9e, 0x40, 0xcd, 0x34, 0x28, 0xd6, 0xa0, 0xb9, 0xbb, 0x6c, 0xbd,
	0xd8, 0x06, 0xb6, 0xfa, 0xe9, 0xa2, 0x2d, 0x16, 0x14, 0x2d, 0x0d, 0xc0, 0xa2, 0x4a, 0xb9, 0x00,
	0x0c, 0xec, 0x21, 0xb4, 0x2c, 0x0c, 0xa3, 0xd4, 0x09, 0x6e, 0x1a, 0x19, 0xc6, 0x78, 0x98, 0xd4,
	0xc1, 0x0b, 0xe8, 0xf5, 0xbc, 0x69, 0xb5, 0xb7, 0x9f, 0xd1, 0x6b, 0x4c, 0xe8, 0x1b, 0x58, 0x4b,
	0x2e, 0xe2, 0xf1, 0x38, 0x14, 0xda, 0x51, 0x75, 0x76, 0x67, 0xd8, 0xb7, 0xa0, 0x15, 0xfa, 0xca,
	0xbc, 0x88, 0x0b, 0x53, 0xe8, 0xda, 0xdc, 0x2f, 0x3a, 0x12, 0xba, 0xc4, 0x4f, 0x61, 0x35, 0x1b,
	0xba, 0xd7, 0xe3, 0x11, 0xc3, 0x41, 0x6e, 0x24, 0x0d, 0xa6, 0xe2, 0x3f, 0xe4, 0x11, 0x23, 0x2f,
	0xc0, 0xb1, 0xd8, 0x71, 0x38, 0xe0, 0x36, 0x04, 0x34, 0x69, 0xa0, 0xc9, 0x1d, 0xa3, 0xff, 0x18,
	0x0e, 0xb8, 0x7e, 0xaa, 0x32, 0xec, 0xfc, 0xba, 0x08, 0x35, 0x5b, 0xe2, 0x07, 0x00, 0xa6, 0x84,
	0xe9, 0x3e, 0x6e, 0x18, 0xc9, 0xa9, 0x54, 0x15, 0xb3, 0xea, 0x5c, 0x5d, 0xdb, 0x46, 0x6a, 0x2a,
	0xf6, 0x0a, 0x5a, 0x16, 0x36, 0xe7, 0x6c, 0x35, 0x0d, 0xde, 0x4c, 0x55, 0xba, 0xf7, 0xcb, 0x5f,
	0xb2, 0xf7, 0x2b, 0xb3, 0xf6, 0xfe, 0x5d, 0xa8, 0x86, 0x7c, 0x44, 0xc3, 0x0b, 0x2c, 0x6a, 0xc3,
	0x35, 0x27, 0xb2, 0x0d, 0x15, 0x21, 0xe3, 0x5b, 0xa7, 0x43, 0x03, 0xa6, 0xd6, 0x5a, 0x7d, 0xfe,
	0xb5, 0x46, 0xa6, 0x57, 0x2e, 0xf9, 0x13, 0x2c, 0x0b, 0xce, 0x7b, 0xd8, 0xb5, 0xb9, 0xf5, 0xd6,
	0x56, 0xe2, 0x33, 0x7a, 0x6d, 0x32, 0xfa, 0x67, 0x58, 0x56, 0xa3, 0x23, 0x22, 0x1e, 0xe5, 0x33,
	0xbf, 0x64, 0xc5, 0x06, 0xf8, 0x08, 0xda, 0xbe, 0x60, 0x72, 0xc4, 0xf3, 0x23, 0xd5, 0xd2, 0x42,
	0x03, 0x7a, 0x01, 0x8e, 0xbd, 0xf5, 0x9c, 0xb2, 0x0b, 0x6f, 0x28, 0xa9, 0xc8, 0xaf, 0xaf, 0x3b,
	0xe6, 0x7a, 0xa5, 0x7e, 0x2b, 0xa9, 0x30, 0x86, 0xcf, 0xe1, 0x9e, 0xb5, 0x99, 0x7c, 0x4e, 0x45,
	0xdb, 0x19, 0xf5, 0x51, 0xfe, 0x55, 0xbb, 0x60, 0x15, 0x5e, 0xfe, 0x75, 0x7a, 0x63, 0xad, 0x19,
	0xe5, 0x49, 0xf6, 0x91, 0x2e, 0xac, 0xc5, 0x21, 0x15, 0x11, 0x65, 0x8a, 0x50, 0x78, 0x3d, 0x1e,
	0x53, 0x7f, 0x68, 0x2b, 0xf4, 0x70, 0xf2, 0x2b, 0xf4, 0x21, 0x85, 0x1e, 0x22, 0xd2, 0x25, 0xf1,
	0xa4, 0x28, 0xea, 0xfc, 0x54, 0x86, 0xfb, 0x37, 0x5a, 0xa8, 0xbe, 0xb3, 0x51, 0x99, 0x05, 0x37,
	0xd9, 0x77, 0x56, 0x3d, 0x7f, 0x3d, 0xf6, 0x60, 0x25, 0x05, 0x32, 0x96, 0x94, 0x24, 0xf3, 0x21,
	0x7d, 0x1f, 0x0e, 0xf6, 0xa9, 0xb8, 0xd8, 0xd3, 0x5a, 0x37, 0x71, 0x6c, 0x04, 0xe4, 0x31, 0x54,
	0x75, 0xd2, 0x8a, 0x87, 0xc1, 0x28, 0xc9, 0x2b, 0x35, 0x9b, 0x3a, 0xb7, 0xe6, 0x9e, 0xea, 0xad,
	0xf7, 0x98, 0x3e, 0xb1, 0xb7, 0xfc, 0x05, 0x56, 0xe3, 0x34, 0xdb, 0x66, 0x4a, 0x6a, 0x38, 0x25,
	0x2b, 0xa9, 0xc2, 0xd5, 0xf3, 0xf2, 0x0a, 0x32, 0x32, 0x4f, 0x8f, 0x4e, 0xfd, 0xc6, 0xd1, 0x59,
	0x4e, 0xb1, 0xa7, 0x38, 0x44, 0x07, 0x90, 0x11, 0xe9, 0x15, 0xd1, 0x98, 0xbd, 0x1b, 0x53, 0x13,
	0xdc, 0x12, 0xb6, 0xd3, 0x3d, 0xb3, 0xd5, 0x90, 0x61, 0xd4, 0x4d, 0xa7, 0x1f, 0x68, 0xd9, 0xd4,
	0xb8, 0x36, 0xe7, 0x1c, 0xd7, 0xef, 0x16, 0x61, 0x29, 0x4f, 0x70, 0xc8, 0x0b, 0x68, 0xb1, 0x71,
	0x18, 0x72, 0xa1, 0x08, 0x11, 0x0f, 0x4c, 0x87, 0xac, 0x4f, 0xd3, 0x21, 0x1e, 0xb8, 0x4d, 0x83,
	0x54, 0x07, 0xf2, 0x0f, 0x68, 0xb2, 0x4f, 0x9c, 0x5d, 0x20, 0x73, 0x8c, 0x9c, 0x45, 0xcc, 0xd3,
	0x83, 0x22, 0xbb, 0x03, 0x05, 0x43, 0x0e, 0x09, 0xcc, 0xfe, 0x8c, 0xc8, 0xbf, 0x60, 0x45, 0xdb,
	0x2b, 0x2e, 0x8d, 0x61, 0x44, 0x4e, 0xa9, 0xd8, 0x09, 0x3a, 0x38, 0x1e, 0xca, 0x4b, 0x8c, 0x68,
	0x89, 0x65, 0x8f, 0x18, 0x81, 0x7a, 0xb9, 0xf7, 0xc9, 0x8f, 0x62, 0x19, 0x5e, 0x3b, 0x15, 0x74,
	0x72, 0x43, 0x04, 0x0a, 0xf9, 0x5a, 0x03, 0x3b, 0xbf, 0x94, 0x60, 0x45, 0xb5, 0x8e, 0xda, 0x04,
	0xf3, 0x10, 0xf7, 0x09, 0x7a, 0xbd, 0x38, 0x8b, 0x5e, 0x3f, 0x85, 0x06, 0xe2, 0xb1, 0x44, 0x85,
	0xe4, 0xbd, 0xae, 0xf4, 0x2a, 0x8a, 0x69, 0x2a, 0x5e, 0x9e, 0x9b, 0x8a, 0xff, 0x1f, 0x36, 0x52,
	0x92, 0x98, 0x38, 0x09, 0xf9, 0x67, 0x9f, 0x5f, 0x46, 0x26, 0x1b, 0x9b, 0x53, 0xe4, 0xdc, 0x3a,
	0x74, 0x11, 0xe7, 0x3a, 0xfd, 0x62, 0x45, 0x34, 0xc9, 0xb7, 0xab, 0x5f, 0xcb, 0xb7, 0x6b, 0x5f,
	0xc5, 0xb7, 0xe7, 0xfd, 0x30, 0xfd, 0x5c, 0x86, 0x7b, 0x37, 0xc4, 0x7a, 0x5b, 0x89, 0x1f, 0x42,
	0x4b, 0xab, 0x72, 0xdb, 0x4f, 0x33, 0xcd, 0x5b, 0x38, 0x79, 0xa9, 0x98, 0x93, 0xbf, 0x06, 0xa2,
	0xbd, 0xe5, 0x88, 0x71, 0x79, 0xe6, 0x4e, 0x58, 0x41, 0xab, 0x2c, 0x29, 0x9e, 0x22, 0x9e, 0x95,
	0x02, 0xe2, 0xb9, 0x09, 0x4d, 0x03, 0xca, 0xd0, 0x66, 0xd0, 0x22, 0xe4, 0x93, 0xd3, 0xcc, 0xb4,
	0x36, 0x0f, 0x33, 0xad, 0x4f, 0x33, 0xd3, 0x2c, 0x97, 0x69, 0x7c, 0x09, 0x97, 0x81, 0x2f, 0xfc,
	0x3f, 0x6c, 0x73, 0xd6, 0x90, 0xbd, 0x85, 0xf5, 0x84, 0x91, 0x66, 0xb3, 0xdc, 0x9a, 0x99, 0x65,
	0x62, 0x59, 0x69, 0x9a, 0xe7, 0xce, 0xf7, 0x0b, 0x70, 0xa7, 0x70, 0xeb, 0xe4, 0x06, 0x74, 0xe6,
	0xa2, 0x6c, 0xb1, 0xcc, 0x69, 0x62, 0xd3, 0xd9, 0x75, 0xb9, 0x70, 0xeb, 0xa6, 0xc3, 0x39, 0x4f,
	0x37, 0x1d, 0xae, 0xcc, 0xce, 0x0f, 0x8b, 0x05, 0xaf, 0xc3, 0x1d, 0xf0, 0x14, 0x1a, 0xfa, 0x0a,
	0x1a, 0x04, 0x37, 0x7c, 0xe4, 0x51, 0xbf, 0x17, 0x04, 0x8a, 0x9c, 0x69, 0xec, 0x38, 0x52, 0x33,
	0x40, 0x47, 0x1c, 0x5f, 0xd3, 0x70, 0xdb, 0x28, 0xfe, 0x18, 0xf1, 0xf0, 0x94, 0x1a, 0x96, 0x9e,
	0xe2, 0x46, 0xf2, 0xdc, 0x1f, 0x6a, 0xce, 0xab, 0x58, 0xba, 0x45, 0xbe, 0x43, 0x31, 0x79, 0x09,
	0x7a, 0xb5, 0xcf, 0xdb, 0xe1, 0xfa, 0xb5, 0xd8, 0xda, 0xf7, 0x41, 0x3f, 0xcd, 0xf3, 0x03, 0xec,
	0xea, 0x86, 0x5b, 0xc3, 0xf3, 0x49, 0xa0, 0x78, 0xad, 0x59, 0x1a, 0x86, 0xd7, 0xea, 0x53, 0x86,
	0xef, 0xd6, 0xb2, 0x7c, 0xb7, 0xf3, 0x6d, 0xa6, 0x7a, 0xb9, 0x0f, 0xcf, 0x1f, 0xff, 0xca, 0xed,
	0x16, 0x7d, 0xe5, 0x56, 0x13, 0xbb, 0xa2, 0x2f, 0x5b, 0xe7, 0xbf, 0xd0, 0x48, 0x6f, 0xde, 0x84,
	0x92, 0x0c, 0x07, 0xc5, 0x35, 0x51, 0x1a, 0xb2, 0x0e, 0x95, 0xd8, 0x8f, 0x87, 0xb6, 0x08, 0xfa,
	0xa0, 0xa4, 0x9f, 0xe9, 0x70, 0x6c, 0x13, 0xae, 0x0f, 0xfb, 0xfb, 0xb0, 0xc9, 0xe4, 0xa8, 0x7b,
	0xe5, 0x53, 0x31, 0x10, 0xb4, 0x7b, 0x79, 0x79, 0x69, 0x1d, 0xda, 0x86, 0xfb, 0xdf, 0xe6, 0xc0,
	0x8f, 0x3f, 0x8d, 0xcf, 0xbb, 0x4c, 0x8e, 0x76, 0xae, 0x04, 0x63, 0xfa, 0xef, 0x5d, 0x51, 0xf2,
	0x97, 0xab, 0x73, 0xfd, 0xf7, 0xb0, 0x67, 0xbf, 0x07, 0x00, 0x00, 0xff, 0xff, 0x00, 0x8a, 0xc1,
	0x64, 0x31, 0x13, 0x00, 0x00,
}
