// Code generated by protoc-gen-go.
// source: common/common.proto
// DO NOT EDIT!

/*
Package common is a generated protocol buffer package.

It is generated from these files:
	common/common.proto

It has these top-level messages:
	ChainCodeResponse
	AppVo
	OperateInfo
	LedgerFile
	OrgBankAccount
*/
package common

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// 调用 cc 返回的数据格式定义(通用)
type ChainCodeResponse struct {
	// 状态编码定义:
	// 0 = 成功
	// !0 = 失败错误码定义
	//      1000 = 参数格式错误
	//      1001 = 未知方法错误
	//      1002 = protobuf数据转换错误
	//      4004 = 数据不存在错误
	//      5000 = cc服务执行错误
	//      可以根据具体业务新增错误编码,编码格式统一定义在6000以后
	Code    int32  `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
	Result  []byte `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
}

func (m *ChainCodeResponse) Reset()                    { *m = ChainCodeResponse{} }
func (m *ChainCodeResponse) String() string            { return proto.CompactTextString(m) }
func (*ChainCodeResponse) ProtoMessage()               {}
func (*ChainCodeResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ChainCodeResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *ChainCodeResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *ChainCodeResponse) GetResult() []byte {
	if m != nil {
		return m.Result
	}
	return nil
}

// 机构摘要
type AppVo struct {
	AppId   string `protobuf:"bytes,1,opt,name=appId" json:"appId,omitempty"`
	AppName string `protobuf:"bytes,2,opt,name=appName" json:"appName,omitempty"`
	Type    string `protobuf:"bytes,3,opt,name=type" json:"type,omitempty"`
}

func (m *AppVo) Reset()                    { *m = AppVo{} }
func (m *AppVo) String() string            { return proto.CompactTextString(m) }
func (*AppVo) ProtoMessage()               {}
func (*AppVo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *AppVo) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *AppVo) GetAppName() string {
	if m != nil {
		return m.AppName
	}
	return ""
}

func (m *AppVo) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

// 数据操作信息
type OperateInfo struct {
	// 创建操作信息
	Creater    *AppVo                     `protobuf:"bytes,1,opt,name=creater" json:"creater,omitempty"`
	CreateTime *google_protobuf.Timestamp `protobuf:"bytes,2,opt,name=create_time,json=createTime" json:"create_time,omitempty"`
	CreaterIp  string                     `protobuf:"bytes,3,opt,name=creater_ip,json=createrIp" json:"creater_ip,omitempty"`
	// 更新操作信息
	LastUser *AppVo                     `protobuf:"bytes,4,opt,name=last_user,json=lastUser" json:"last_user,omitempty"`
	LastTime *google_protobuf.Timestamp `protobuf:"bytes,5,opt,name=last_time,json=lastTime" json:"last_time,omitempty"`
	LastIp   string                     `protobuf:"bytes,6,opt,name=last_ip,json=lastIp" json:"last_ip,omitempty"`
}

func (m *OperateInfo) Reset()                    { *m = OperateInfo{} }
func (m *OperateInfo) String() string            { return proto.CompactTextString(m) }
func (*OperateInfo) ProtoMessage()               {}
func (*OperateInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *OperateInfo) GetCreater() *AppVo {
	if m != nil {
		return m.Creater
	}
	return nil
}

func (m *OperateInfo) GetCreateTime() *google_protobuf.Timestamp {
	if m != nil {
		return m.CreateTime
	}
	return nil
}

func (m *OperateInfo) GetCreaterIp() string {
	if m != nil {
		return m.CreaterIp
	}
	return ""
}

func (m *OperateInfo) GetLastUser() *AppVo {
	if m != nil {
		return m.LastUser
	}
	return nil
}

func (m *OperateInfo) GetLastTime() *google_protobuf.Timestamp {
	if m != nil {
		return m.LastTime
	}
	return nil
}

func (m *OperateInfo) GetLastIp() string {
	if m != nil {
		return m.LastIp
	}
	return ""
}

// 账本链上文件
type LedgerFile struct {
	Url         string       `protobuf:"bytes,1,opt,name=url" json:"url,omitempty"`
	Data        []byte       `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Sha256      string       `protobuf:"bytes,3,opt,name=sha256" json:"sha256,omitempty"`
	Name        string       `protobuf:"bytes,4,opt,name=name" json:"name,omitempty"`
	Size        int64        `protobuf:"varint,5,opt,name=size" json:"size,omitempty"`
	Type        string       `protobuf:"bytes,6,opt,name=type" json:"type,omitempty"`
	OperateInfo *OperateInfo `protobuf:"bytes,7,opt,name=operate_info,json=operateInfo" json:"operate_info,omitempty"`
}

func (m *LedgerFile) Reset()                    { *m = LedgerFile{} }
func (m *LedgerFile) String() string            { return proto.CompactTextString(m) }
func (*LedgerFile) ProtoMessage()               {}
func (*LedgerFile) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *LedgerFile) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *LedgerFile) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *LedgerFile) GetSha256() string {
	if m != nil {
		return m.Sha256
	}
	return ""
}

func (m *LedgerFile) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *LedgerFile) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *LedgerFile) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *LedgerFile) GetOperateInfo() *OperateInfo {
	if m != nil {
		return m.OperateInfo
	}
	return nil
}

// 银行账户信息
type OrgBankAccount struct {
	Account    string `protobuf:"bytes,1,opt,name=account" json:"account,omitempty"`
	BankName   string `protobuf:"bytes,2,opt,name=bank_name,json=bankName" json:"bank_name,omitempty"`
	BankBranch string `protobuf:"bytes,3,opt,name=bank_branch,json=bankBranch" json:"bank_branch,omitempty"`
}

func (m *OrgBankAccount) Reset()                    { *m = OrgBankAccount{} }
func (m *OrgBankAccount) String() string            { return proto.CompactTextString(m) }
func (*OrgBankAccount) ProtoMessage()               {}
func (*OrgBankAccount) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *OrgBankAccount) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *OrgBankAccount) GetBankName() string {
	if m != nil {
		return m.BankName
	}
	return ""
}

func (m *OrgBankAccount) GetBankBranch() string {
	if m != nil {
		return m.BankBranch
	}
	return ""
}

func init() {
	proto.RegisterType((*ChainCodeResponse)(nil), "protos.ChainCodeResponse")
	proto.RegisterType((*AppVo)(nil), "protos.AppVo")
	proto.RegisterType((*OperateInfo)(nil), "protos.OperateInfo")
	proto.RegisterType((*LedgerFile)(nil), "protos.LedgerFile")
	proto.RegisterType((*OrgBankAccount)(nil), "protos.OrgBankAccount")
}

func init() { proto.RegisterFile("common/common.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 503 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x84, 0x53, 0xdf, 0x8b, 0x13, 0x31,
	0x10, 0xa6, 0xd7, 0x5f, 0xb7, 0xb3, 0x55, 0x34, 0x27, 0xba, 0x9c, 0x94, 0x2b, 0x7d, 0xb1, 0xf8,
	0xb0, 0x85, 0x8a, 0xe7, 0x83, 0x20, 0x5c, 0x0f, 0x84, 0xa2, 0x78, 0x10, 0x54, 0xd0, 0x97, 0x92,
	0xee, 0xa6, 0xbb, 0xcb, 0xed, 0x26, 0x21, 0xc9, 0xd2, 0xd3, 0xbf, 0xc2, 0xbf, 0xc8, 0xbf, 0x4d,
	0x32, 0xc9, 0x5e, 0x7d, 0x10, 0x7c, 0xda, 0xf9, 0x26, 0xb3, 0x93, 0x6f, 0xbe, 0x2f, 0x03, 0x67,
	0x99, 0x6c, 0x1a, 0x29, 0x96, 0xfe, 0x93, 0x2a, 0x2d, 0xad, 0x24, 0x23, 0xfc, 0x98, 0xf3, 0x8b,
	0x42, 0xca, 0xa2, 0xe6, 0x4b, 0x84, 0xbb, 0x76, 0xbf, 0xb4, 0x55, 0xc3, 0x8d, 0x65, 0x8d, 0xf2,
	0x85, 0xf3, 0x6f, 0xf0, 0xf8, 0xba, 0x64, 0x95, 0xb8, 0x96, 0x39, 0xa7, 0xdc, 0x28, 0x29, 0x0c,
	0x27, 0x04, 0x06, 0x99, 0xcc, 0x79, 0xd2, 0x9b, 0xf5, 0x16, 0x43, 0x8a, 0x31, 0x49, 0x60, 0xdc,
	0x70, 0x63, 0x58, 0xc1, 0x93, 0x93, 0x59, 0x6f, 0x11, 0xd1, 0x0e, 0x92, 0xa7, 0x30, 0xd2, 0xdc,
	0xb4, 0xb5, 0x4d, 0xfa, 0xb3, 0xde, 0x62, 0x42, 0x03, 0x9a, 0x7f, 0x80, 0xe1, 0x95, 0x52, 0x5f,
	0x25, 0x79, 0x02, 0x43, 0xa6, 0xd4, 0x26, 0xc7, 0x7e, 0x11, 0xf5, 0xc0, 0x35, 0x64, 0x4a, 0x7d,
	0x62, 0xcd, 0x7d, 0xc3, 0x00, 0xdd, 0xf5, 0xf6, 0x87, 0xe2, 0xd8, 0x2e, 0xa2, 0x18, 0xcf, 0x7f,
	0x9d, 0x40, 0x7c, 0xa3, 0xb8, 0x66, 0x96, 0x6f, 0xc4, 0x5e, 0x92, 0x17, 0x30, 0xce, 0x34, 0x67,
	0x96, 0x6b, 0xec, 0x1a, 0xaf, 0x1e, 0xf8, 0x81, 0x4c, 0x8a, 0x77, 0xd2, 0xee, 0x94, 0xbc, 0x85,
	0xd8, 0x87, 0x5b, 0x37, 0x3a, 0x5e, 0x15, 0xaf, 0xce, 0x53, 0xaf, 0x4b, 0xda, 0xe9, 0x92, 0x7e,
	0xee, 0x74, 0xa1, 0xe0, 0xcb, 0x5d, 0x82, 0x4c, 0x21, 0x20, 0xbd, 0xad, 0x54, 0xe0, 0x13, 0x85,
	0xcc, 0x46, 0x91, 0x97, 0x10, 0xd5, 0xcc, 0xd8, 0x6d, 0x6b, 0xb8, 0x4e, 0x06, 0xff, 0xa2, 0x71,
	0xea, 0xce, 0xbf, 0x18, 0xae, 0xc9, 0x9b, 0x50, 0x8b, 0x2c, 0x86, 0xff, 0x65, 0x81, 0x3f, 0x22,
	0x87, 0x67, 0x30, 0xc6, 0x1f, 0x2b, 0x95, 0x8c, 0x90, 0xc0, 0xc8, 0xc1, 0x8d, 0x9a, 0xff, 0xee,
	0x01, 0x7c, 0xe4, 0x79, 0xc1, 0xf5, 0xfb, 0xaa, 0xe6, 0xe4, 0x11, 0xf4, 0x5b, 0x5d, 0x07, 0x8d,
	0x5d, 0xe8, 0x74, 0xcc, 0x99, 0x65, 0x38, 0xf3, 0x84, 0x62, 0xec, 0xcc, 0x32, 0x25, 0x5b, 0xbd,
	0xbe, 0x0c, 0xd3, 0x04, 0xe4, 0x6a, 0x85, 0xb3, 0x62, 0xe0, 0x35, 0x17, 0xc1, 0x07, 0x53, 0xfd,
	0xf4, 0x6c, 0xfb, 0x14, 0xe3, 0x7b, 0x6f, 0x46, 0x47, 0x6f, 0xc8, 0x25, 0x4c, 0xa4, 0xb7, 0x66,
	0x5b, 0x89, 0xbd, 0x4c, 0xc6, 0x38, 0xdd, 0x59, 0xa7, 0xc4, 0x5f, 0xb6, 0xd1, 0x58, 0x1e, 0xc1,
	0xbc, 0x84, 0x87, 0x37, 0xba, 0x58, 0x33, 0x71, 0x7b, 0x95, 0x65, 0xb2, 0x15, 0x16, 0xdf, 0x84,
	0x0f, 0xc3, 0x1c, 0x1d, 0x24, 0xcf, 0x21, 0xda, 0x31, 0x71, 0xbb, 0x15, 0xc7, 0xf7, 0x72, 0xea,
	0x12, 0xf8, 0x60, 0x2e, 0x20, 0xc6, 0xc3, 0x9d, 0x66, 0x22, 0x2b, 0xc3, 0x64, 0xe0, 0x52, 0x6b,
	0xcc, 0xac, 0xdf, 0xc1, 0x34, 0x93, 0x4d, 0x7a, 0x57, 0x31, 0x51, 0x08, 0x96, 0x1e, 0x0e, 0x87,
	0x8e, 0x9c, 0xdf, 0x9a, 0xef, 0xd3, 0xa2, 0xb2, 0x65, 0xbb, 0x73, 0x70, 0x79, 0x27, 0xb2, 0xcc,
	0x2f, 0x8c, 0x09, 0x4b, 0xb5, 0xf3, 0xeb, 0xf4, 0xea, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x54,
	0x5f, 0xa4, 0x90, 0x6c, 0x03, 0x00, 0x00,
}
